### PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# number of dimension : https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html

scalar.ndim

0

In [4]:
# Get tensor back as Python int

scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[2,4],
                       [1,3]])
MATRIX

tensor([[2, 4],
        [1, 3]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([2, 4])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,3,9],
                        [2,4,6],
                        [5,9,7]]])
TENSOR

tensor([[[1, 3, 9],
         [2, 4, 6],
         [5, 9, 7]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 3, 9],
        [2, 4, 6],
        [5, 9, 7]])

In [16]:
MY_TENSOR = torch.tensor([[[
                              [1,3,9,4], # <0
                              [2,4,8,6], # <1
#                              [4,1,6,3]  # <2
#                              ^ ^ ^ ^
#                              0 1 2 3
                            ]]])
MY_TENSOR

tensor([[[[1, 3, 9, 4],
          [2, 4, 8, 6]]]])

In [17]:
MY_TENSOR.ndim

4

In [18]:
MY_TENSOR.shape

torch.Size([1, 1, 2, 4])

## Tensor Exercise

In [19]:
TENSOR = torch.tensor([[1,2,3], [4,5,6]])
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
TENSOR.ndim

2

In [21]:
TENSOR.shape

torch.Size([2, 3])

In [22]:
TENSOR[0]

tensor([1, 2, 3])

In [23]:
TENSOR2 = torch.tensor([
    [2,1,4],
    [1,5,2]
])
TENSOR2

tensor([[2, 1, 4],
        [1, 5, 2]])

In [24]:
TENSOR2.ndim

2

In [25]:
TENSOR2.shape

torch.Size([2, 3])

In [26]:
TENSOR3 = torch.tensor([
    [2,1,4],
    [1,5,2],
    [7,5,9]
])
TENSOR3

tensor([[2, 1, 4],
        [1, 5, 2],
        [7, 5, 9]])

In [27]:
TENSOR3.ndim

2

In [28]:
TENSOR3.shape

torch.Size([3, 3])

In [29]:
TENSOR4 = torch.tensor([[
    [1,2,3,2],
    [7,8,9,7],
    [4,5,6,9]
]])

TENSOR4

tensor([[[1, 2, 3, 2],
         [7, 8, 9, 7],
         [4, 5, 6, 9]]])

In [30]:
TENSOR4.ndim

3

In [31]:
TENSOR4.shape

torch.Size([1, 3, 4])

In [32]:
TENSOR5 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ]
                ]
            ]
        ]
    ]
)

TENSOR5

tensor([[[[[[1, 2],
            [4, 1],
            [6, 8]]]]]])

In [33]:
TENSOR5.ndim # expected 6

6

In [34]:
TENSOR5.shape #expected tensor.Size([1,1,1,1,3,2])

torch.Size([1, 1, 1, 1, 3, 2])

In [35]:
TENSOR6 = torch.tensor(
    [
            [
              [1,2],
              [4,8],
              [3,9]
            ],
            [
              [5,6],
              [7,9],
              [4,1]
            ]

    ]
)

TENSOR6

tensor([[[1, 2],
         [4, 8],
         [3, 9]],

        [[5, 6],
         [7, 9],
         [4, 1]]])

In [36]:
TENSOR6.ndim

3

In [37]:
TENSOR6.shape

torch.Size([2, 3, 2])

In [38]:
TENSOR7 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ],
                [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ]
    ]
)
TENSOR7

tensor([[[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]],



         [[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]]],




        [[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
      

In [39]:
TENSOR7.ndim

6

In [40]:
TENSOR7.shape

torch.Size([2, 2, 3, 2, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html

In [41]:
# Create a random tensors of size (3,4)
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.6877, 0.8168, 0.5291, 0.8306],
        [0.5964, 0.1718, 0.0364, 0.7685],
        [0.4173, 0.8082, 0.9488, 0.3509]])

In [42]:
random_tensors.ndim

2

In [43]:
random_tensors = torch.rand(10, 8)
random_tensors

tensor([[0.9527, 0.1472, 0.1003, 0.8875, 0.5196, 0.0139, 0.7032, 0.3350],
        [0.6991, 0.0631, 0.2206, 0.0782, 0.6035, 0.0065, 0.2624, 0.7943],
        [0.6772, 0.6007, 0.9491, 0.6079, 0.2274, 0.5019, 0.6414, 0.1097],
        [0.5003, 0.9155, 0.4998, 0.8757, 0.3700, 0.2231, 0.0427, 0.3691],
        [0.0880, 0.9128, 0.4001, 0.2344, 0.5629, 0.6454, 0.1341, 0.0415],
        [0.1357, 0.5165, 0.9959, 0.0912, 0.3346, 0.8965, 0.9643, 0.4861],
        [0.6640, 0.5459, 0.7222, 0.7276, 0.0710, 0.6125, 0.3477, 0.5629],
        [0.2523, 0.7847, 0.2762, 0.4484, 0.8090, 0.3889, 0.7283, 0.0476],
        [0.0560, 0.4578, 0.6408, 0.1838, 0.6381, 0.7178, 0.4496, 0.3657],
        [0.3618, 0.6165, 0.4674, 0.3587, 0.4949, 0.6572, 0.6092, 0.8843]])

In [44]:
random_tensors.ndim

2

In [45]:
random_tensors = torch.rand(10, 100, 100)
random_tensors

tensor([[[0.0395, 0.6591, 0.4777,  ..., 0.2252, 0.0169, 0.2507],
         [0.3652, 0.0069, 0.5695,  ..., 0.5090, 0.9337, 0.6168],
         [0.4742, 0.3927, 0.6433,  ..., 0.9681, 0.0795, 0.0178],
         ...,
         [0.6636, 0.4165, 0.6202,  ..., 0.4661, 0.3468, 0.7002],
         [0.5041, 0.9343, 0.6820,  ..., 0.7374, 0.6603, 0.9131],
         [0.8428, 0.3732, 0.8954,  ..., 0.6173, 0.0251, 0.9563]],

        [[0.3799, 0.4599, 0.6312,  ..., 0.8066, 0.3590, 0.0468],
         [0.9995, 0.4274, 0.4740,  ..., 0.6793, 0.4107, 0.8580],
         [0.5248, 0.4499, 0.7373,  ..., 0.0626, 0.3408, 0.6288],
         ...,
         [0.4493, 0.0676, 0.0645,  ..., 0.2178, 0.3427, 0.9370],
         [0.7910, 0.0856, 0.2428,  ..., 0.5288, 0.7833, 0.7312],
         [0.3785, 0.5959, 0.9851,  ..., 0.6181, 0.8067, 0.8879]],

        [[0.5860, 0.3625, 0.3741,  ..., 0.4199, 0.0922, 0.1674],
         [0.1172, 0.3932, 0.5827,  ..., 0.1802, 0.0711, 0.4565],
         [0.0397, 0.3228, 0.2800,  ..., 0.6742, 0.4612, 0.

In [46]:
random_tensors.ndim

3

In [47]:
random_tensors = torch.rand(10, 10, 10, 10, 10)
random_tensors

tensor([[[[[9.8387e-01, 4.0714e-01, 7.7389e-01,  ..., 4.9270e-03,
            3.0799e-01, 5.1205e-01],
           [2.3343e-01, 3.5702e-01, 7.6783e-01,  ..., 7.7426e-01,
            3.2994e-02, 6.4043e-01],
           [7.9255e-01, 7.6943e-01, 6.4641e-01,  ..., 7.1132e-01,
            4.8322e-01, 9.4951e-01],
           ...,
           [7.7165e-01, 1.8643e-01, 7.7013e-01,  ..., 9.7420e-01,
            3.1091e-01, 9.7014e-01],
           [2.4313e-01, 6.2849e-01, 3.2862e-01,  ..., 6.5060e-01,
            1.7824e-01, 4.1927e-01],
           [6.2839e-01, 3.2727e-01, 5.0617e-01,  ..., 6.6812e-01,
            4.7295e-01, 9.5179e-01]],

          [[8.4369e-01, 7.5995e-01, 2.3178e-01,  ..., 7.0524e-01,
            8.4660e-01, 6.3005e-01],
           [6.2020e-01, 6.9034e-01, 9.6067e-01,  ..., 7.1514e-01,
            9.1220e-01, 6.1098e-01],
           [8.1081e-01, 6.3782e-01, 8.0880e-02,  ..., 7.4954e-01,
            1.4425e-01, 6.5778e-01],
           ...,
           [6.8883e-01, 6.6076e-01, 6.0

In [48]:
random_tensors.ndim

5

In [49]:
random_tensors.shape

torch.Size([10, 10, 10, 10, 10])

In [50]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [51]:
itensor = torch.rand(224, 224, 3)
itensor

tensor([[[0.6565, 0.9436, 0.3133],
         [0.8771, 0.2922, 0.6794],
         [0.4719, 0.0086, 0.5719],
         ...,
         [0.5986, 0.0302, 0.4222],
         [0.9094, 0.0724, 0.9912],
         [0.2158, 0.2404, 0.0052]],

        [[0.9575, 0.7736, 0.2296],
         [0.7208, 0.1672, 0.7315],
         [0.7814, 0.0721, 0.2650],
         ...,
         [0.1300, 0.8731, 0.9514],
         [0.6911, 0.5623, 0.3959],
         [0.2889, 0.7389, 0.5659]],

        [[0.3126, 0.6054, 0.7285],
         [0.7344, 0.3970, 0.8645],
         [0.4762, 0.8312, 0.8713],
         ...,
         [0.4490, 0.1620, 0.6872],
         [0.3587, 0.6766, 0.1070],
         [0.7494, 0.2850, 0.8806]],

        ...,

        [[0.4602, 0.8708, 0.1184],
         [0.2877, 0.7985, 0.2793],
         [0.9733, 0.4503, 0.0105],
         ...,
         [0.0101, 0.4819, 0.6221],
         [0.1878, 0.2236, 0.8181],
         [0.8885, 0.2390, 0.8241]],

        [[0.1284, 0.6425, 0.3945],
         [0.9595, 0.7998, 0.7853],
         [0.

In [52]:
itensor.ndim

3

## Zeros and ones

In [53]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
new_random_tensor = torch.rand(3,4)
new_random_tensor

tensor([[0.9688, 0.1942, 0.5978, 0.7060],
        [0.1687, 0.3925, 0.8846, 0.3926],
        [0.4332, 0.9865, 0.1488, 0.3468]])

In [55]:
zeros * new_random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

`torch.arange()` : https://pytorch.org/docs/stable/generated/torch.arange.html

In [58]:
# Use torch.range(1,11)
# Depreciated message:::>>>> UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
zero_to_hundred = torch.arange(start=0, end=100, step=10)
zero_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Creating tensors like
# when we have to define a tensor shape from a pre-defined tensor and overwrite with zeros
new_tensor_from_zero_to_hundred_tensor = torch.zeros_like(input=zero_to_hundred)
new_tensor_from_zero_to_hundred_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one the 3 big errors you'll run into with PyTorch && Deep Learning:

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device


Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)



In [61]:
# default tensor datatype - default tensor datatype is depends on input input of the given tensor

# here i will set `int` numbers for the tensor, so the default datatype of the tensor will be `int64`
# so the default is `int64` for int numbers
default_datatype_tensor = torch.tensor([5,8,1,6,2,9])

default_datatype_tensor

tensor([5, 8, 1, 6, 2, 9])

In [62]:
default_datatype_tensor.dtype

torch.int64

In [63]:
# here i will set `float` numbers for the tensor, so the default datatype would be `float32`
# so the default is `float32` for int numbers
default_datatype_tensor = torch.tensor([3.1,4.9,6.4,.5])

default_datatype_tensor

tensor([3.1000, 4.9000, 6.4000, 0.5000])

In [64]:
default_datatype_tensor.dtype

torch.float32

In [65]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 2.0, 4.0], dtype=torch.float32) # defined `float32`

float_32_tensor

tensor([3., 2., 4.])

In [66]:
float_32_tensor.dtype

torch.float32

In [67]:
# set float numbers but later define the datatype your want to sent with the tensor
int64_tensor = torch.tensor([4.1,2,4,7], dtype=torch.int64)
int64_tensor

tensor([4, 2, 4, 7])

In [68]:
int64_tensor.dtype

torch.int64

In [69]:
#
float_32_tensor = torch.tensor([7.3,1,9,4.2], dtype=None # what datatype is the tensor (e.g. float32. float16)
                                                        )
float_32_tensor

tensor([7.3000, 1.0000, 9.0000, 4.2000])

In [70]:
float_32_tensor.dtype

torch.float32

In [71]:
# with more parameters
float_32_tensor = torch.tensor([4.1,7.5,7.8],
                               dtype = None, # set  datatypes:  e.g. float16, float32 :> available datatypes: https://pytorch.org/docs/stable/tensors.html || https://en.wikipedia.org/wiki/Precision_(computer_science)
                               device = None, # what device is your tensor on e.g. 'cpu' or 'cuda' mean gpu
                               requires_grad = False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([4.1000, 7.5000, 7.8000])

In [72]:
# converted the datatype 'float_32' to 'float_16' of a tensor

# how might we change the datatype of the tensor
float16_tensor = float_32_tensor.type(torch.float16)
float16_tensor

tensor([4.1016, 7.5000, 7.8008], dtype=torch.float16)

In [73]:
### Excercise (DataTypes)

# boolean data types
boolean_tensor = torch.tensor([1,0,0,1,0,1,1], dtype=torch.bool)

boolean_tensor

tensor([ True, False, False,  True, False,  True,  True])

In [74]:
boolean_tensor.dtype

torch.bool

In [75]:
# requires_grad = True
MY_TENSOR = torch.tensor([[1.1, 9.3], [3.6, 6.7]], requires_grad=True)

OUT = MY_TENSOR.pow(2).sum()
OUT.backward()
MY_TENSOR.grad

tensor([[ 2.2000, 18.6000],
        [ 7.2000, 13.4000]])

## Tensor Views
PyTorch allows a tensor to be a `View` of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting `View` avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

For example, to get a view of an existing tensor `first_tensor`, you can call `t.view(...)`.


**Source:** https://pytorch.org/docs/stable/tensor_view.html#tensor-view-doc

In [76]:
# example
first_tensor = torch.rand(4,4)
first_tensor

tensor([[0.3965, 0.1059, 0.0498, 0.5192],
        [0.4244, 0.3572, 0.9717, 0.2418],
        [0.4284, 0.1308, 0.1899, 0.9524],
        [0.0273, 0.5565, 0.5814, 0.4956]])

In [77]:
second_tensor = first_tensor.view(2,8)
second_tensor

tensor([[0.3965, 0.1059, 0.0498, 0.5192, 0.4244, 0.3572, 0.9717, 0.2418],
        [0.4284, 0.1308, 0.1899, 0.9524, 0.0273, 0.5565, 0.5814, 0.4956]])

In [78]:
# check if the two tensors sharing the same data

# using `first_tensor.storage()` you will get deprecated message,
first_tensor.storage().data_ptr() == second_tensor.storage().data_ptr() # `first_tensor` and `second_tensor` share the same underlying data

<ipython-input-78-b48ea378aafa>:4: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  first_tensor.storage().data_ptr() == second_tensor.storage().data_ptr() # `first_tensor` and `second_tensor` share the same underlying data


True

In [79]:
# Modifying view tensor(e.g.`second_tensor`) changes base tensor(e.g. `first_tensor`) as well

# first extract value of given indices
second_tensor[0][0]

# updating value
second_tensor[0][0] = 0.401

# check whether the value of the first_tensor is updated or not
first_tensor[0][0]

# print the whole tensor
first_tensor

#    Note:** Since views share underlying data with its base tensor, if you edit the data in the view, it will be reflected in the base tensor as well.



tensor([[0.4010, 0.1059, 0.0498, 0.5192],
        [0.4244, 0.3572, 0.9717, 0.2418],
        [0.4284, 0.1308, 0.1899, 0.9524],
        [0.0273, 0.5565, 0.5814, 0.4956]])

Typically a PyTorch op returns a new tensor as output, e.g. `add()`. But in case of view ops, outputs are views of input tensors to avoid unnecessary data copy. No data movement occurs when creating a view, view tensor just changes the way it interprets the same data. Taking a view of contiguous tensor could potentially produce a non-contiguous tensor. Users should pay additional attention as contiguity might have implicit performance impact. `transpose()` is a common example.

**Source:** https://pytorch.org/docs/stable/tensor_view.html#tensor-views

In [80]:
first_tensor.is_contiguous()

True

In [81]:
second_tensor.is_contiguous()

True

In [82]:
# create new base tensor
base_tensor = torch.tensor([[0,1],[2,3]])
print(base_tensor.is_contiguous())
base_tensor

True


tensor([[0, 1],
        [2, 3]])

In [83]:
view_tensor = base_tensor.transpose(0,1) # `view_tensor` if a view of `base_tensor`. No data movement happened here
view_tensor

tensor([[0, 2],
        [1, 3]])

In [84]:
# `view_tensor`(transpose) might be non-contiguous
# so, let's check whether it's right or not
view_tensor.is_contiguous()

False

In [88]:
# To get contiguous tensor, call `.contiguous()` to enfore
# copying data when `view_tensor` is not contiguous
copy_tensor = view_tensor.contiguous()
copy_tensor

# check now, if `copy_tensor` is contiguous or not
copy_tensor.is_contiguous()

True