# Exercises

## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)
* The documentation on [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html)

In [2]:
import torch

In [3]:
# default float datatype is `float32`

default_float_datatype_tensor = torch.tensor([0.5, 0.1, 0.7, 0.3])
default_float_datatype_tensor, default_float_datatype_tensor.dtype

(tensor([0.5000, 0.1000, 0.7000, 0.3000]), torch.float32)

In [4]:
# torch.Tensor

## Data Types

# float32 datatype
# create tensor
float_32_tensor = torch.tensor([4, 7, 8], dtype=torch.float) # `torch.float` or, `torch.float32`
float_32_tensor, float_32_tensor.dtype

(tensor([4., 7., 8.]), torch.float32)

In [5]:
float_32Tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
float_32Tensor

tensor([1., 2., 3.])

In [6]:
# float64 datatype
float_64_tensor = torch.tensor([1, 4, 2], dtype=torch.float64) # `torch.float64` or, `torch.double`
float_64_tensor, float_64_tensor.dtype

(tensor([1., 4., 2.], dtype=torch.float64), torch.float64)

In [7]:
float_64Tensor = torch.tensor([6, 9, 2], dtype=torch.double)
float_64Tensor, float_64Tensor.dtype

(tensor([6., 9., 2.], dtype=torch.float64), torch.float64)

In [8]:
'''
1. Sometimes referred to as binary16: uses 1 sign, 5 exponent, and 10 significand bits. Useful when precision is important at the expense of range.
'''

# 1. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.float16), torch.float16)

In [9]:
#
float_16Tensor = torch.tensor([8, 2, 6], dtype=torch.half)
float_16Tensor, float_16Tensor.dtype

(tensor([8., 2., 6.], dtype=torch.float16), torch.float16)

In [10]:
'''
Sometimes referred to as Brain Floating Point: uses 1 sign, 8 exponent, and 7 significand bits. Useful when range is important, since it has the same number of exponent bits as float32
'''

# 2. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.bfloat16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.bfloat16), torch.bfloat16)

In [11]:
# default integer datatype is `int64`
default_int_datatype_tensor = torch.tensor([6,1,9])
default_int_datatype_tensor, default_int_datatype_tensor.dtype

(tensor([6, 1, 9]), torch.int64)

In [12]:
# integers(signed) datatypes
int_8_tensor = torch.tensor([4,8,1], dtype=torch.int8)
int_8_tensor, int_8_tensor.dtype

(tensor([4, 8, 1], dtype=torch.int8), torch.int8)

In [13]:
int_16_tensor = torch.tensor([6,8,2], dtype=torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([6, 8, 2], dtype=torch.int16), torch.int16)

In [14]:
int_16_or_short_tensor = torch.tensor([7,1,9], dtype=torch.short)
int_16_or_short_tensor, int_16_or_short_tensor.dtype

(tensor([7, 1, 9], dtype=torch.int16), torch.int16)

In [15]:
# 32bit integers (signed)
int_32_tensor = torch.tensor([6,3,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([6, 3, 9], dtype=torch.int32), torch.int32)

In [16]:
int32Tensor = torch.tensor([6,1,9], dtype=torch.int)
int32Tensor, int32Tensor.dtype

(tensor([6, 1, 9], dtype=torch.int32), torch.int32)

In [17]:
int_64_Tensor = torch.tensor([7,1,8], dtype=torch.int64)
int_64_Tensor, int_64_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [18]:
int_64_or_long_Tensor = torch.tensor([7,1,8], dtype=torch.long)
int_64_or_long_Tensor, int_64_or_long_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [19]:
# boolean datatype
boolean_tensor = torch.tensor([1,0,1,0,1], dtype=torch.bool)
boolean_tensor, boolean_tensor.dtype

(tensor([ True, False,  True, False,  True]), torch.bool)

In [20]:
## backward compatibility
# 32-bit floating point
x = torch.FloatTensor([1,8,5])
x, x.dtype

(tensor([1., 8., 5.]), torch.float32)

In [21]:
# converting datatype (float32 to float64)

# 1.
y = x.type(torch.DoubleTensor)
y, y.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [22]:
# 2.
z = x.type(torch.float64)
z, z.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [23]:
# 3.
w = x.type(torch.double)
w, w.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [24]:
# 64-bit floating point
a = torch.DoubleTensor([7,1,5,4])
a

tensor([7., 1., 5., 4.], dtype=torch.float64)

In [25]:
# 16-bit floating point
b = torch.HalfTensor([4,7,1])
b

tensor([4., 7., 1.], dtype=torch.float16)

In [26]:
# 16-bit floating point
c = torch.BFloat16Tensor([5,8,4])
c

tensor([5., 8., 4.], dtype=torch.bfloat16)

In [27]:
# 8-bit integer (unsigned)
d = torch.ByteTensor([1,2,3])
d

tensor([1, 2, 3], dtype=torch.uint8)

In [28]:
# 8-bit integer (signed)
e = torch.CharTensor([3,5,4])
e

tensor([3, 5, 4], dtype=torch.int8)

In [29]:
# 16-bit integer (signed)
f = torch.ShortTensor([5,7,9])
f

tensor([5, 7, 9], dtype=torch.int16)

In [30]:
# 32-bit integer (signed)
g = torch.IntTensor([6,1,5])
g

tensor([6, 1, 5], dtype=torch.int32)

In [31]:
# 64-bit integer (signed)
h = torch.LongTensor([5,2,9])
h

tensor([5, 2, 9])

In [32]:
# Boolean
i = torch.BoolTensor([0,1,0])
i, i.dtype

(tensor([False,  True, False]), torch.bool)

In [33]:
# factory function - `torch.empty()`
k = torch.empty(size=(3,3),dtype=torch.float16)
k, k.ndim, k.shape

(tensor([[ 3.4668e-02, -2.7990e-04,  1.3938e+02],
         [ 0.0000e+00,  8.3160e-04, -2.7370e-04],
         [ 1.3938e+02,  0.0000e+00,  4.7684e-06]], dtype=torch.float16),
 2,
 torch.Size([3, 3]))

In [34]:
# initializing and basic operations
m = torch.tensor([
    [1., -1.],
    [1., -1.]
])
m

tensor([[ 1., -1.],
        [ 1., -1.]])

In [35]:
import numpy as np

from_numpy = torch.tensor(
    np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])
)
from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
check = torch.tensor([1, 2, 3], dtype=torch.float16)
check.requires_grad_()

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [37]:
# another method
check2 = torch.tensor([1.0, 4.1, 9.2])
check2.detach_(), check2.dtype

(tensor([1.0000, 4.1000, 9.2000]), torch.float32)

In [38]:
y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
y

<ipython-input-38-94b980d24cc2>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


tensor([1.0000, 4.1000, 9.2000])

In [39]:
#
TENSOR_X = torch.tensor([2.1, 6.4, 3.9], requires_grad=True)

TENSOR_Y = TENSOR_X.detach()

TENSOR_Y.requires_grad_()

tensor([2.1000, 6.4000, 3.9000], requires_grad=True)

In [40]:
checkTensor = torch.Tensor([1, 2, 3])
checkTensor, checkTensor.dtype

(tensor([1., 2., 3.]), torch.float32)

# Tensor class reference
```
class     torch.Tensor
```
There are a few main ways to create a tensor, depending on your use case.

1. To create a tensor with pre-existing data, use `torch.tensor()`.

2. To create a tensor with specific size, use `torch.*` tensor creation ops (see [Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)).

3. To create a tensor with the same size (and similar types) as another tensor, use `torch.*_like` tensor creation ops (see [Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)).

4. To create a tensor with similar type but different size as another tensor, use `tensor.new_*` creation ops.



In [41]:
# 1
first_tensor = torch.tensor([6, 3, 2])
first_tensor

tensor([6, 3, 2])

In [42]:
# 2 torch.*

# 2.1 - torch.zeros(dimension or size)
second_tensor = torch.zeros(3, 4)
second_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
# 2.2 torch.zeros_like(source_tensor)
source_tensor = torch.tensor([[3, 4, 6], [1, 8, 3]])

third_tensor = torch.zeros_like(source_tensor)
third_tensor

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
# 2.3 torch.ones(dimension)
ones_tensor = torch.ones(5,8)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
# 2.4 torch.ones_like(source_tensor)
source_tensor = torch.tensor([[3, 6, 7], [9,5,8]])
ones_like_tensor = torch.ones_like(source_tensor)
print(f"source_tensor = \n{source_tensor}")
print(f"ones_like_tensor = \n{ones_like_tensor}")

source_tensor = 
tensor([[3, 6, 7],
        [9, 5, 8]])
ones_like_tensor = 
tensor([[1, 1, 1],
        [1, 1, 1]])


In [46]:
# 2.5 torch.arange(start, end, step) - returns a 1-D tensor of size [end - start / step]
arange_tensor = torch.arange(1, 15, 2)
arange_tensor

tensor([ 1,  3,  5,  7,  9, 11, 13])

In [47]:
# 2.6 torch.linspace(start, end, step) - Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
linspace_tensor = torch.linspace(60, 100, 14)
linspace_tensor

tensor([ 60.0000,  63.0769,  66.1538,  69.2308,  72.3077,  75.3846,  78.4615,
         81.5385,  84.6154,  87.6923,  90.7692,  93.8462,  96.9231, 100.0000])

In [48]:
# 2.7 torch.logspace(start, end, step, base) - Creates a one-dimensional tensor of size steps whose values are evenly spaced from base start base_start to base_end base end, inclusive, on a logarithmic scale with base base.
logspace_tensor = torch.logspace(3, 9, 5) # by default base=10.0
logspace_tensor

tensor([1.0000e+03, 3.1623e+04, 1.0000e+06, 3.1623e+07, 1.0000e+09])

In [49]:
'''
calculation for getting the values of the return Tensor,
value = base ** (start + i * (end-start) / (steps-1)),   where `i` is the index of the value in the sequence, ranging from 0 to `steps-1`
'''

logspace_tensor = torch.logspace(0, 2, 10)
logspace_tensor

tensor([  1.0000,   1.6681,   2.7826,   4.6416,   7.7426,  12.9155,  21.5443,
         35.9381,  59.9484, 100.0000])

In [50]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=1)
exploring_logspace

tensor([1.2589])

In [51]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=2)
exploring_logspace

tensor([ 1.2589, 10.0000])

In [52]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=3)
exploring_logspace

tensor([ 1.2589,  3.5481, 10.0000])

In [53]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=4)
exploring_logspace

tensor([ 1.2589,  2.5119,  5.0119, 10.0000])

In [54]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=5)
exploring_logspace

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [55]:
'''
calculation of `torch.logspace(start=0.1, end=1.0, steps=10)`

values of the return tensor are:

1st_value  = base ** (start + (steps - 10) * (end - start / steps - 1)) [equivalent of (base ** start), if you put those values in the equation you will understand why it's equivalent with `base ** start`]
2nd_value  = base ** (start + (steps - 9) * (end - start / steps - 1))
3rd_value  = base ** (start + (steps - 8) * (end - start / steps - 1))
4th_value  = base ** (start + (steps - 7) * (end - start / steps - 1))
5th_value  = base ** (start + (steps - 6) * (end - start / steps - 1))
6th_value  = base ** (start + (steps - 5) * (end - start / steps - 1))
7th_value  = base ** (start + (steps - 4) * (end - start / steps - 1))
6th_value  = base ** (start + (steps - 3) * (end - start / steps - 1))
8th_value  = base ** (start + (steps - 2) * (end - start / steps - 1))
10th_value = base ** (start + (steps - 1) * (end - start / steps - 1)) [equivalent of (base ** end), if you put those values in the equation you will understand why it's equivalent with `base ** end`]

notice: for user defined purposes if we mention `i` instead of (steps - 10, 9, 8, 7, 6, 5, 4, 3, 2, 1) that means the index of the `i` will be start `0` to `steps - 1`
        as for this example 0 to 9 because `steps = 10`

source: https://pytorch.org/docs/stable/generated/torch.logspace.html#torch.logspace
'''


exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=10)
exploring_logspace

tensor([ 1.2589,  1.5849,  1.9953,  2.5119,  3.1623,  3.9811,  5.0119,  6.3096,
         7.9433, 10.0000])

In [56]:
# 2.8 torch.eye() -> Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
eye_tensor = torch.eye(5) # paramers of eye() are, 1. n (which will be a int number) -> the number of rows 2. m (which will be a int number) -> the number of columns with default being n
eye_tensor, eye_tensor.shape, eye_tensor.ndim

(tensor([[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]),
 torch.Size([5, 5]),
 2)

In [57]:
eye_tensor = torch.eye(8, 8)
eye_tensor, eye_tensor.shape, eye_tensor.ndim

(tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1.]]),
 torch.Size([8, 8]),
 2)

In [58]:
# 2.9 - torch.empty(size of the tensor) -> Return a tensor filled with uninitialized data.
empty_tensor = torch.empty((3, 4))
empty_tensor

tensor([[-2.3456e-31,  3.1696e-41, -2.3468e-31,  3.1696e-41],
        [ 1.1210e-43,  0.0000e+00,  8.9683e-44,  0.0000e+00],
        [ 2.1108e-33,  3.1700e-41,  0.0000e+00,  0.0000e+00]])

In [59]:
# 3.0 - torch.empty_like(input_tensor) -> Returns an uninitialized tensor with the same size as input.
input_tensor = torch.empty((3, 4), dtype=torch.int32)

empty_like_tensor = torch.empty_like(input_tensor)
empty_like_tensor

tensor([[  395050384,       32370, -1936331312,       22619],
        [          0,           0,           0,           0],
        [          0,           5,   845505073,  1714905444]],
       dtype=torch.int32)

In [60]:
# 3.1 ->

In [61]:
x = torch.rand(3, 100)
x, x.shape, x.ndim

(tensor([[0.2225, 0.8272, 0.8495, 0.2230, 0.1300, 0.6622, 0.2589, 0.7612, 0.2594,
          0.5193, 0.0385, 0.7154, 0.3667, 0.7194, 0.0328, 0.5778, 0.1596, 0.5522,
          0.5075, 0.8634, 0.0450, 0.8129, 0.5704, 0.3377, 0.3761, 0.7073, 0.9595,
          0.2742, 0.3896, 0.6634, 0.2268, 0.5888, 0.6690, 0.8060, 0.5898, 0.5103,
          0.1133, 0.3719, 0.5008, 0.4044, 0.9761, 0.7954, 0.0099, 0.5582, 0.9315,
          0.1823, 0.2614, 0.8251, 0.3622, 0.4618, 0.7223, 0.5109, 0.8507, 0.8715,
          0.7895, 0.9193, 0.8150, 0.9633, 0.9000, 0.8655, 0.2940, 0.2677, 0.8190,
          0.0250, 0.0623, 0.0918, 0.2613, 0.0157, 0.1205, 0.1962, 0.2237, 0.9418,
          0.2600, 0.4928, 0.4695, 0.4622, 0.7844, 0.3673, 0.8923, 0.0583, 0.5771,
          0.9902, 0.1939, 0.3486, 0.1887, 0.6599, 0.9314, 0.8730, 0.5603, 0.9759,
          0.3326, 0.2863, 0.3238, 0.7568, 0.6609, 0.4485, 0.2311, 0.3893, 0.1209,
          0.0891],
         [0.0450, 0.5896, 0.7386, 0.0456, 0.4534, 0.8285, 0.9387, 0.4965, 0.333

In [62]:
x.stride()

(100, 1)

In [63]:
# Create a 2D array
x = torch.tensor(
    [

              [0, 1, 2, 3, 4,7],
              [5, 6, 7, 8, 9,8],

    ], dtype=torch.int32)

x.stride(), x.ndim

((6, 1), 2)

In [64]:
x[0][0].item() #x_00

0

In [65]:
#x_10
x[1][0]

tensor(5, dtype=torch.int32)

In [66]:
import numpy as np

t = torch.tensor(np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype=np.int32))
t.stride()

(5, 1)

In [67]:
x = torch.arange(12).view((3,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [68]:
idx = (2, 1)
item = x[idx].item()
item

9

# Indexing, Slicing, Joining, Mutating Ops[

# [2. Create a random tensor with shape(7,7)](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [69]:
# create random tensor
random_tensor = torch.randn(7, 7)
random_tensor

tensor([[-0.3246, -0.3857,  1.1784, -1.2926, -0.5480, -0.5270, -0.2692],
        [-0.9490,  1.0686,  2.0382,  0.7114, -0.7548,  0.2829,  1.7928],
        [ 0.1547, -0.0721,  1.0118,  1.2507,  0.7381, -0.1641,  1.2392],
        [-0.7809,  0.1459, -2.7896, -1.6401,  1.9034, -1.2799,  2.2027],
        [-0.7678, -1.5774,  0.8857,  0.2117,  0.9074, -0.9237,  0.1675],
        [-2.3758,  0.3130,  0.3988, -0.3359, -2.3012, -0.6675,  0.1027],
        [-0.6531, -0.3888,  0.2083, -1.5376,  0.7577,  0.2895,  1.0553]])

# [3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape(1,7) (hint: you may have to transpose the second tensor)](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [70]:
second_random_tensor = torch.randn(1, 7)
second_random_tensor

tensor([[-0.3082, -0.5727,  0.1038,  1.2601,  0.3893, -1.4318, -0.3652]])

In [71]:
# multiplication
#mul_tensor = torch.matmul(random_tensor, second_random_tensor) # generate error because of shape issue(mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7))
#mul_tensor

In [72]:
# hence we have to transpose second_random_tensor to solve the issue
transpose_of_second_random_tensor = second_random_tensor.T
transpose_of_second_random_tensor

tensor([[-0.3082],
        [-0.5727],
        [ 0.1038],
        [ 1.2601],
        [ 0.3893],
        [-1.4318],
        [-0.3652]])

In [73]:
# again try to multiplication
mul_tensor = torch.matmul(random_tensor, transpose_of_second_random_tensor)
mul_tensor

tensor([[-0.5460],
        [-0.5652],
        [ 1.7444],
        [-0.4300],
        [ 3.1133],
        [ 0.1935],
        [-1.9971]])

#[4. Set the random seed to 0 and do exercises 2 & 3 over again.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [74]:
# set the manual seed
torch.manual_seed(0)

# create two random tensor
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

#[5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to `1234`.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [75]:
# set the random seed on the GPU
torch.cuda.manual_seed(1234)

# [6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [76]:
# set random seed
torch.manual_seed(1234)

# check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# create two random tensors on GPU
tensor1 = torch.rand(2, 3).to(device)
print(tensor1)
tensor2 = torch.rand(2, 3).to(device)
print(tensor2)



cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


# [7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [77]:
# transpose of second tensor(tensor2)
transpose_of_tensor2 = tensor2.T
print(transpose_of_tensor2.shape)

# multiplication
mul_tensor1_tensor2 = torch.matmul(tensor1, transpose_of_tensor2)
mul_tensor1_tensor2, mul_tensor1_tensor2.shape

torch.Size([3, 2])


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

# [8. Find the maximum and minimum values of the output of exercise no. 7](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [78]:
# maximum
max_of_mul_tensor1_tensor2 = torch.max(mul_tensor1_tensor2)
print(max_of_mul_tensor1_tensor2)

# minimum
min_of_mul_tensor1_tensor2 = torch.min(mul_tensor1_tensor2)
print(min_of_mul_tensor1_tensor2)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')


# [9. Find the maximum and minimum index values of the output of exercise no. 7.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [79]:
#
arg_max = torch.argmax(mul_tensor1_tensor2)

arg_min = torch.argmin(mul_tensor1_tensor2)

arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [80]:
mul_tensor1_tensor2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

# [10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [82]:
# create random tensor
torch.manual_seed(7)
r_tensor = torch.rand(1, 1, 1, 10)
print(r_tensor)
print(r_tensor.shape)

# remove the single dimensions
new_tensor = torch.squeeze(r_tensor)
print(new_tensor)
print(new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
