### PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# number of dimension : https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html

scalar.ndim

0

In [ ]:
# Get tensor back as Python int

scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[2,4],
                       [1,3]])
MATRIX

tensor([[2, 4],
        [1, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([2, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,3,9],
                        [2,4,6],
                        [5,9,7]]])
TENSOR

tensor([[[1, 3, 9],
         [2, 4, 6],
         [5, 9, 7]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 3, 9],
        [2, 4, 6],
        [5, 9, 7]])

In [ ]:
MY_TENSOR = torch.tensor([[[
                              [1,3,9,4], # <0
                              [2,4,8,6], # <1
#                              [4,1,6,3]  # <2
#                              ^ ^ ^ ^
#                              0 1 2 3
                            ]]])
MY_TENSOR

tensor([[[[1, 3, 9, 4],
          [2, 4, 8, 6]]]])

In [ ]:
MY_TENSOR.ndim

4

In [ ]:
MY_TENSOR.shape

torch.Size([1, 1, 2, 4])

## Tensor Exercise

In [ ]:
TENSOR = torch.tensor([[1,2,3], [4,5,6]])
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
TENSOR.ndim

2

In [ ]:
TENSOR.shape

torch.Size([2, 3])

In [ ]:
TENSOR[0]

tensor([1, 2, 3])

In [ ]:
TENSOR2 = torch.tensor([
    [2,1,4],
    [1,5,2]
])
TENSOR2

tensor([[2, 1, 4],
        [1, 5, 2]])

In [ ]:
TENSOR2.ndim

2

In [ ]:
TENSOR2.shape

torch.Size([2, 3])

In [ ]:
TENSOR3 = torch.tensor([
    [2,1,4],
    [1,5,2],
    [7,5,9]
])
TENSOR3

tensor([[2, 1, 4],
        [1, 5, 2],
        [7, 5, 9]])

In [ ]:
TENSOR3.ndim

2

In [ ]:
TENSOR3.shape

torch.Size([3, 3])

In [ ]:
TENSOR4 = torch.tensor([[
    [1,2,3,2],
    [7,8,9,7],
    [4,5,6,9]
]])

TENSOR4

tensor([[[1, 2, 3, 2],
         [7, 8, 9, 7],
         [4, 5, 6, 9]]])

In [ ]:
TENSOR4.ndim

3

In [ ]:
TENSOR4.shape

torch.Size([1, 3, 4])

In [ ]:
TENSOR5 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ]
                ]
            ]
        ]
    ]
)

TENSOR5

tensor([[[[[[1, 2],
            [4, 1],
            [6, 8]]]]]])

In [ ]:
TENSOR5.ndim # expected 6

6

In [ ]:
TENSOR5.shape #expected tensor.Size([1,1,1,1,3,2])

torch.Size([1, 1, 1, 1, 3, 2])

In [ ]:
TENSOR6 = torch.tensor(
    [
            [
              [1,2],
              [4,8],
              [3,9]
            ],
            [
              [5,6],
              [7,9],
              [4,1]
            ]

    ]
)

TENSOR6

tensor([[[1, 2],
         [4, 8],
         [3, 9]],

        [[5, 6],
         [7, 9],
         [4, 1]]])

In [ ]:
TENSOR6.ndim

3

In [ ]:
TENSOR6.shape

torch.Size([2, 3, 2])

In [ ]:
TENSOR7 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ],
                [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ]
    ]
)
TENSOR7

tensor([[[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]],



         [[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]]],




        [[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
      

In [ ]:
TENSOR7.ndim

6

In [ ]:
TENSOR7.shape

torch.Size([2, 2, 3, 2, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensors of size (3,4)
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.0160, 0.2551, 0.9102, 0.8558],
        [0.6812, 0.5730, 0.5749, 0.8331],
        [0.4640, 0.2258, 0.7661, 0.4874]])

In [ ]:
random_tensors.ndim

2

In [ ]:
random_tensors = torch.rand(10, 8)
random_tensors

tensor([[0.9966, 0.3521, 0.8111, 0.6158, 0.7110, 0.9669, 0.1130, 0.5041],
        [0.0667, 0.1323, 0.6992, 0.0140, 0.9048, 0.7053, 0.9616, 0.9586],
        [0.3916, 0.0991, 0.6050, 0.8508, 0.3090, 0.3900, 0.9358, 0.8233],
        [0.5459, 0.5050, 0.2579, 0.8662, 0.1302, 0.4428, 0.0124, 0.4773],
        [0.2868, 0.3923, 0.6779, 0.4758, 0.0682, 0.8428, 0.1544, 0.9814],
        [0.5454, 0.6739, 0.5846, 0.2028, 0.7854, 0.2089, 0.6250, 0.9299],
        [0.8509, 0.0255, 0.7838, 0.4547, 0.8791, 0.4556, 0.7417, 0.7460],
        [0.2570, 0.7981, 0.0762, 0.8109, 0.8216, 0.0741, 0.2076, 0.8409],
        [0.4031, 0.3537, 0.3032, 0.0079, 0.1886, 0.3817, 0.0853, 0.9678],
        [0.7926, 0.5758, 0.8539, 0.8235, 0.2765, 0.0619, 0.5861, 0.2852]])

In [ ]:
random_tensors.ndim

2

In [ ]:
random_tensors = torch.rand(10, 100, 100)
random_tensors

tensor([[[0.3569, 0.5505, 0.1569,  ..., 0.8784, 0.5369, 0.5435],
         [0.5041, 0.1348, 0.9507,  ..., 0.0787, 0.4062, 0.0963],
         [0.0295, 0.9692, 0.7344,  ..., 0.0824, 0.9303, 0.8993],
         ...,
         [0.7534, 0.6253, 0.7621,  ..., 0.1594, 0.2096, 0.1603],
         [0.7839, 0.5559, 0.0813,  ..., 0.8504, 0.1762, 0.1096],
         [0.3347, 0.4671, 0.1558,  ..., 0.1929, 0.4356, 0.5727]],

        [[0.3477, 0.3417, 0.9173,  ..., 0.7531, 0.0303, 0.4437],
         [0.6732, 0.1120, 0.0937,  ..., 0.8254, 0.3127, 0.9206],
         [0.3072, 0.5202, 0.2249,  ..., 0.4200, 0.7621, 0.6103],
         ...,
         [0.1709, 0.6286, 0.8697,  ..., 0.7050, 0.1933, 0.0899],
         [0.3851, 0.5163, 0.1728,  ..., 0.1254, 0.6661, 0.3725],
         [0.2139, 0.8705, 0.8934,  ..., 0.8812, 0.9263, 0.6391]],

        [[0.8205, 0.6196, 0.5728,  ..., 0.6823, 0.3126, 0.0435],
         [0.4709, 0.5802, 0.7737,  ..., 0.0969, 0.6297, 0.6035],
         [0.4731, 0.2755, 0.2267,  ..., 0.1592, 0.6208, 0.

In [ ]:
random_tensors.ndim

3

In [ ]:
random_tensors = torch.rand(10, 10, 10, 10, 10)
random_tensors

tensor([[[[[6.5135e-01, 4.6933e-01, 1.3959e-01,  ..., 8.5467e-01,
            7.5798e-01, 2.5279e-01],
           [8.3826e-01, 9.7371e-01, 6.2153e-01,  ..., 6.3514e-01,
            7.2930e-01, 4.8227e-01],
           [7.1838e-01, 6.0664e-01, 3.1236e-01,  ..., 4.8302e-01,
            9.0600e-01, 3.9168e-01],
           ...,
           [7.3418e-01, 4.1151e-02, 8.7796e-01,  ..., 6.5647e-01,
            8.3455e-02, 3.9876e-03],
           [8.7194e-01, 4.7225e-01, 5.0627e-01,  ..., 2.2028e-01,
            6.0455e-02, 3.7495e-01],
           [4.7776e-01, 9.7095e-01, 6.2787e-01,  ..., 3.4651e-01,
            9.9104e-01, 5.5199e-03]],

          [[7.2755e-01, 6.7844e-01, 5.7460e-01,  ..., 3.8619e-01,
            8.9395e-01, 4.8063e-01],
           [8.3300e-01, 6.7645e-02, 7.3078e-01,  ..., 5.4736e-01,
            4.5671e-01, 1.2199e-01],
           [9.3479e-01, 2.0411e-01, 3.1555e-01,  ..., 7.4329e-01,
            9.2328e-01, 3.1401e-01],
           ...,
           [9.6733e-01, 2.1812e-01, 1.9

In [ ]:
random_tensors.ndim

5

In [ ]:
random_tensors.shape

torch.Size([10, 10, 10, 10, 10])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
itensor = torch.rand(224, 224, 3)
itensor

tensor([[[0.1319, 0.9856, 0.4166],
         [0.5539, 0.1591, 0.2057],
         [0.1117, 0.8236, 0.1594],
         ...,
         [0.3235, 0.7658, 0.0590],
         [0.1472, 0.2476, 0.6100],
         [0.0641, 0.1482, 0.9446]],

        [[0.7351, 0.0996, 0.2253],
         [0.3091, 0.0736, 0.1439],
         [0.6947, 0.5199, 0.5858],
         ...,
         [0.5050, 0.8844, 0.5576],
         [0.6373, 0.6658, 0.8820],
         [0.8759, 0.1205, 0.2625]],

        [[0.4865, 0.6677, 0.2449],
         [0.6517, 0.9582, 0.7843],
         [0.0192, 0.8989, 0.5133],
         ...,
         [0.6570, 0.1133, 0.7915],
         [0.1626, 0.5725, 0.2173],
         [0.7775, 0.3962, 0.7995]],

        ...,

        [[0.4538, 0.9146, 0.9122],
         [0.3644, 0.9204, 0.4333],
         [0.6585, 0.6790, 0.4118],
         ...,
         [0.0576, 0.4423, 0.3367],
         [0.7208, 0.8979, 0.2872],
         [0.2088, 0.2272, 0.8646]],

        [[0.5082, 0.2734, 0.5771],
         [0.7411, 0.8590, 0.4911],
         [0.

In [ ]:
itensor.ndim

3

## Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
new_random_tensor = torch.rand(3,4)
new_random_tensor

tensor([[0.6639, 0.6956, 0.2701, 0.2381],
        [0.9182, 0.1797, 0.1304, 0.0825],
        [0.6163, 0.7122, 0.5463, 0.8034]])

In [ ]:
zeros * new_random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

`torch.arange()` : https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
# Use torch.range(1,11)
# Depreciated message:::>>>> UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
zero_to_hundred = torch.arange(start=0, end=100, step=10)
zero_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Creating tensors like
# when we have to define a tensor shape from a pre-defined tensor and overwrite with zeros
new_tensor_from_zero_to_hundred_tensor = torch.zeros_like(input=zero_to_hundred)
new_tensor_from_zero_to_hundred_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one the 3 big errors you'll run into with PyTorch && Deep Learning:

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device


Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)



In [ ]:
# default tensor datatype - default tensor datatype is depends on input input of the given tensor

# here i will set `int` numbers for the tensor, so the default datatype of the tensor will be `int64`
# so the default is `int64` for int numbers
default_datatype_tensor = torch.tensor([5,8,1,6,2,9])

default_datatype_tensor

tensor([5, 8, 1, 6, 2, 9])

In [ ]:
default_datatype_tensor.dtype

torch.int64

In [ ]:
# here i will set `float` numbers for the tensor, so the default datatype would be `float32`
# so the default is `float32` for int numbers
default_datatype_tensor = torch.tensor([3.1,4.9,6.4,.5])

default_datatype_tensor

tensor([3.1000, 4.9000, 6.4000, 0.5000])

In [ ]:
default_datatype_tensor.dtype

torch.float32

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 2.0, 4.0], dtype=torch.float32) # defined `float32`

float_32_tensor

tensor([3., 2., 4.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# set float numbers but later define the datatype your want to sent with the tensor
int64_tensor = torch.tensor([4.1,2,4,7], dtype=torch.int64)
int64_tensor

tensor([4, 2, 4, 7])

In [ ]:
int64_tensor.dtype

torch.int64

In [ ]:
#
float_32_tensor = torch.tensor([7.3,1,9,4.2], dtype=None # what datatype is the tensor (e.g. float32. float16)
                                                        )
float_32_tensor

tensor([7.3000, 1.0000, 9.0000, 4.2000])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# with more parameters
float_32_tensor = torch.tensor([4.1,7.5,7.8],
                               dtype = None, # set  datatypes:  e.g. float16, float32 :> available datatypes: https://pytorch.org/docs/stable/tensors.html || https://en.wikipedia.org/wiki/Precision_(computer_science)
                               device = None, # what device is your tensor on e.g. 'cpu' or 'cuda' mean gpu
                               requires_grad = False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([4.1000, 7.5000, 7.8000])

In [ ]:
# converted the datatype 'float_32' to 'float_16' of a tensor

# how might we change the datatype of the tensor
float16_tensor = float_32_tensor.type(torch.float16)
float16_tensor

tensor([4.1016, 7.5000, 7.8008], dtype=torch.float16)

# Excercise (DataTypes)

In [ ]:
# boolean data types
boolean_tensor = torch.tensor([1,0,0,1,0,1,1], dtype=torch.bool)

boolean_tensor

tensor([ True, False, False,  True, False,  True,  True])

In [ ]:
boolean_tensor.dtype

torch.bool

In [ ]:
# requires_grad = True
MY_TENSOR = torch.tensor([[1.1, 9.3], [3.6, 6.7]], requires_grad=True)

OUT = MY_TENSOR.pow(2).sum()
OUT.backward()
MY_TENSOR.grad

tensor([[ 2.2000, 18.6000],
        [ 7.2000, 13.4000]])

## Tensor Views
PyTorch allows a tensor to be a `View` of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting `View` avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

For example, to get a view of an existing tensor `first_tensor`, you can call `t.view(...)`.


**Source:** https://pytorch.org/docs/stable/tensor_view.html#tensor-view-doc

In [ ]:
# example
first_tensor = torch.rand(4,4)
first_tensor

tensor([[0.8912, 0.6526, 0.6819, 0.8979],
        [0.2016, 0.4027, 0.4531, 0.1546],
        [0.0200, 0.1206, 0.3146, 0.2706],
        [0.4275, 0.1275, 0.3710, 0.6446]])

In [ ]:
second_tensor = first_tensor.view(2,8)
second_tensor

tensor([[0.8912, 0.6526, 0.6819, 0.8979, 0.2016, 0.4027, 0.4531, 0.1546],
        [0.0200, 0.1206, 0.3146, 0.2706, 0.4275, 0.1275, 0.3710, 0.6446]])

In [ ]:
# check if the two tensors sharing the same data

# using `first_tensor.storage()` you will get deprecated message, To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
first_tensor.untyped_storage().data_ptr() == second_tensor.untyped_storage().data_ptr() # `first_tensor` and `second_tensor` share the same underlying data

True

In [ ]:
# Modifying view tensor(e.g.`second_tensor`) changes base tensor(e.g. `first_tensor`) as well

# first extract value of given indices
second_tensor[0][0]

# updating value
second_tensor[0][0] = 0.401

# check whether the value of the first_tensor is updated or not
first_tensor[0][0]

# print the whole tensor
first_tensor

#    Note:** Since views share underlying data with its base tensor, if you edit the data in the view, it will be reflected in the base tensor as well.



tensor([[0.4010, 0.6526, 0.6819, 0.8979],
        [0.2016, 0.4027, 0.4531, 0.1546],
        [0.0200, 0.1206, 0.3146, 0.2706],
        [0.4275, 0.1275, 0.3710, 0.6446]])

Typically a PyTorch op returns a new tensor as output, e.g. `add()`. But in case of view ops, outputs are views of input tensors to avoid unnecessary data copy. No data movement occurs when creating a view, view tensor just changes the way it interprets the same data. Taking a view of contiguous tensor could potentially produce a non-contiguous tensor. Users should pay additional attention as contiguity might have implicit performance impact. `transpose()` is a common example.

**Source:** https://pytorch.org/docs/stable/tensor_view.html#tensor-views

In [ ]:
first_tensor.is_contiguous()

True

In [ ]:
second_tensor.is_contiguous()

True

In [ ]:
# create new base tensor
base_tensor = torch.tensor([[0,1],[2,3]])
print(base_tensor.is_contiguous())
base_tensor

True


tensor([[0, 1],
        [2, 3]])

In [ ]:
view_tensor = base_tensor.transpose(0,1) # `view_tensor` if a view of `base_tensor`. No data movement happened here
view_tensor

tensor([[0, 2],
        [1, 3]])

In [ ]:
# `view_tensor`(transpose) might be non-contiguous
# so, let's check whether it's right or not
view_tensor.is_contiguous()

False

In [ ]:
# To get contiguous tensor, call `.contiguous()` to enfore
# copying data when `view_tensor` is not contiguous
copy_tensor = view_tensor.contiguous()
copy_tensor

# check now, if `copy_tensor` is contiguous or not
copy_tensor.is_contiguous()

True

## Arithmetic Operations

In [ ]:
# multiplication with two different datatypes or with same datatype but different bits(e.g. 16 or 32 or 64)

float_16_tensor = torch.tensor([1.1,5.3,6.9], dtype=torch.float16)

float_16_tensor

tensor([1.0996, 5.3008, 6.8984], dtype=torch.float16)

In [ ]:
flotat_32_tensor = torch.tensor([4.7, 4.1,8.3], dtype=torch.float32)

float_32_tensor

tensor([4.1000, 7.5000, 7.8000])

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 4.5084, 39.7559, 53.8078])

In [ ]:
int_32_tensor = torch.tensor([5,8,3], dtype=torch.int32)
int_32_tensor

tensor([5, 8, 3], dtype=torch.int32)

In [ ]:
int_32_tensor * float_32_tensor

tensor([20.5000, 60.0000, 23.4000])

In [ ]:
int_64_tensor = torch.tensor([2,7,9], dtype=torch.int64)
int_64_tensor

tensor([2, 7, 9])

In [ ]:
float_32_tensor * int_64_tensor

tensor([ 8.2000, 52.5000, 70.2000])

In [ ]:
long_tensor = torch.tensor([4,6,9], dtype=torch.long)
long_tensor

tensor([4, 6, 9])

In [ ]:
long_tensor * float_32_tensor

tensor([16.4000, 45.0000, 70.2000])

## Getting information from tensors (tensor attributes)
1.   Tensors not right datatype - to do that get datatype from a tensor, can use `tensor.dtype`
2.   Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3.   Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5559, 0.8261, 0.2269, 0.6167],
        [0.0237, 0.4741, 0.4810, 0.7374],
        [0.5160, 0.5757, 0.6280, 0.0631]])

In [ ]:
# Find out details anout some tensor
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # there are two way to get shape or size of a tensor, 1. with attribute (e.g. some_tensor.shape) 2. with function (e.g. some_tensor.size())
print(f"Device of tensor is on: {some_tensor.device}")

tensor([[0.5559, 0.8261, 0.2269, 0.6167],
        [0.0237, 0.4741, 0.4810, 0.7374],
        [0.5160, 0.5757, 0.6280, 0.0631]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


In [ ]:
check = torch.rand(3,4)
check

tensor([[0.2289, 0.1786, 0.8862, 0.8252],
        [0.4579, 0.5534, 0.8003, 0.3172],
        [0.0937, 0.3911, 0.3381, 0.5244]])

In [ ]:
check.dtype


torch.float32

In [ ]:
deck = check.type(torch.float16)
deck.dtype

torch.float16

In [ ]:
deck

tensor([[0.2289, 0.1786, 0.8862, 0.8252],
        [0.4580, 0.5532, 0.8003, 0.3171],
        [0.0937, 0.3911, 0.3381, 0.5244]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication (Part #1)

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise Multiplication
2. Matrix Multiplication (dot prouct)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html#

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication by torch
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[0] * tensor[0]
print(value)

tensor(3)
CPU times: user 2.73 ms, sys: 0 ns, total: 2.73 ms
Wall time: 4.81 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 66 µs, sys: 11 µs, total: 77 µs
Wall time: 80.8 µs


tensor(14)

### Matrix Multiplication (Part #2)

There are two main rules that performing matrix multiplication needs to stisfy:
1.  The **inner dimensions** must match:
    *   `(3,2) @ (3,2)` won't work
    *   `(2,3) @ (3,2)` will work
    *   `(3,2) @ (2,3)` will work

    ***Note:*** `@` is a attribute in tensor for multiplying two tensor whereas `tensor.matmul()` is a function. e.g. `tensor1 @ tensor2` `==` `torch.matmul(tensor1, tensor2)`
2.  The resulting matrix has the shape of the **outer dimensions**:
    *   `(2,3) @ (3,2)` -> `(2,2)`
    *   `(3,2) @ (2,3)` -> `(3,3)`

#### One of the main errors in matrix multiplication is shape error

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(3,2)) # error occurs

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

In [ ]:
torch.matmul(torch.rand(4,5), torch.rand(5,4))

In [ ]:
torch.matmul(torch.rand(10,4), torch.rand(4, 5))

In [ ]:
# if inner dimension match but different outer dimension
torch.matmul(torch.rand(10,4), torch.rand(4, 6))

### One of the most common errors in deep learning: shape errors

### Matrix Multiplication (Part #3: Dealing with tensor shape errors)


In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's as an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.

**Note:** A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.t() # transpose via function

In [ ]:
tensor_B.T, tensor_B.T.shape #tranpose via attribute

In [ ]:
# second approach to make transpose through function
torch.transpose(tensor_B, 0, 1) # reference:: https://pytorch.org/docs/stable/generated/torch.transpose.html

In [ ]:
# The matrix multiplication operation works when tensorB is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

# Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

In [ ]:
# Find the min
torch.min(x), x.min()

In [ ]:
# Find the max
torch.max(x), x.max()

In [ ]:
# Find the mean **note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

In [ ]:
# Find the sum
torch.sum(x), x.sum()

# Finding the positional min and max of tensors

In [ ]:
x = torch.arange(1, 100, 10)
x

In [ ]:
# Find the position in tensor that has the minimum value with `argmin()` -> returns index position of target tensor where the minimum value occurs.
x.argmin()

In [ ]:
# check the value of the position
print(f"x.argmin().item() = {x.argmin().item()}\n")
x[x.argmin().item()]

In [ ]:
# Find the position in tensor that has the maximum value with `argmax()`
x.argmax()

In [ ]:
# check the value of the position
print(f"x.armax().item() = {x.argmax().item()}\n")
x[x.argmax().item()]

# Reshaping, viewing, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
    * stack - https://pytorch.org/docs/stable/generated/torch.stack.html
    * vstack - https://pytorch.org/docs/stable/generated/torch.vstack.html
    * hstack - https://pytorch.org/docs/stable/generated/torch.hstack.html
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [ ]:
#Let's create a tensor

import torch
x = torch.arange(1., 10)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped = x.reshape(2, 9)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped = x.reshape(0, 9)
x_reshaped, x_reshaped.shape

In [ ]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

In [ ]:
# exercise
y = torch.arange(1., 15)
y, y.shape

In [ ]:
y_reshaped = y.reshape(2,7) # here,, 2x7 or 7x2 (any other combination of two number) = size of the y tensor(which is 14) *required to match
y_reshaped, y_reshaped.shape

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

In [ ]:
# Change z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=2)
x_stacked

# Squeezing, unsqueezing and permuting tensors
`torch.squeeze()` - removes all single dimensions from a target tensor

For example, if input is of shape: (A×1×B×C×1×D)(A×1×B×C×1×D) then the input.squeeze() will be of shape: (A×B×C×D)(A×B×C×D).

When dim is given, a squeeze operation is done only in the given dimension(s). If input is of shape: (A×1×B)(A×1×B), squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape (A×B)(A×B).

**note:** *The returned tensor shares the storage with the input tensor, so changing the contents of one will change the contents of the other.*

source: https://pytorch.org/docs/stable/generated/torch.squeeze.html

In [ ]:
a_reshaped = x_reshaped.reshape(1,9)
a_reshaped

In [ ]:
a_reshaped.shape

In [ ]:
a_reshaped.squeeze()

In [ ]:
a_reshaped.squeeze().shape

In [ ]:
#  removes all of the 1 from the input tensor
eg_tensor = torch.rand(3,1,4,2,6, 1, 8)
eg_tensor

In [ ]:
eg_tensor.shape

In [ ]:
eg_tensor_squeezed = eg_tensor.squeeze()

In [ ]:
eg_tensor_squeezed.shape  ## eg_tensor().squeeze() removes all of the 1 from the input tensor

In [ ]:
print(f"Previous tensor: {eg_tensor}")
print(f"Previous shape: {eg_tensor.shape}")

print(f"New tensor: {eg_tensor.squeeze()}")
print(f"New shape: {eg_tensor.squeeze().shape}")

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)
print(f"Previous target: {eg_tensor_squeezed}")
print(f"Previous shape:{eg_tensor_squeezed.shape}")

eg_tensor_unsqueezed = eg_tensor_squeezed.unsqueeze(dim=0)

print(f"New tensor: {eg_tensor_unsqueezed}")
print(f"New shape: {eg_tensor_unsqueezed.shape}")

In [ ]:
# exercise with `my_tensor.squeeze()`

# create tensor
my_tensor = torch.tensor(
    [
        [
            [1, 2],
            [3, 4],
            [5, 6]
        ]
    ]
)
my_tensor

In [ ]:
my_tensor.shape, my_tensor.ndim

In [ ]:
print(f"Previous tensor:\n {my_tensor}")
print(f"Previous shape: {my_tensor.shape}")
print(f"Previous dimension: {my_tensor.ndim}")

my_tensor_squeezed = my_tensor.squeeze()

print(f"\nLater tensor:\n {my_tensor_squeezed}")
print(f"Later shape: {my_tensor_squeezed.shape}")
print(f"Later dimension: {my_tensor_squeezed.ndim}")

In [ ]:
# exercise with my_tensor_squeezed.unsqueeze()

print(f"Previous tensor:\n {my_tensor_squeezed}")
print(f"Previous shape: {my_tensor_squeezed.shape}")
print(f"Previous dimension: {my_tensor_squeezed.ndim}")

my_tensor_unsqueezed = my_tensor_squeezed.unsqueeze(dim=0)

print(f"\nLater tensor:\n {my_tensor_unsqueezed}")
print(f"Later shape: {my_tensor_unsqueezed.shape}")
print(f"Later dimension: {my_tensor_unsqueezed.ndim}")

In [ ]:
# torch.permute - rearrage the dimensions of a target tensor in a specified order
# permute is use for work with image data

x_original = torch.rand(size=(224, 224, 3)) # [height, widht, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

In [ ]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

In [ ]:
x_original[0, 0, 0] = .4507
x_permuted[0, 0, 0]

# Indexing (selecting data from tensors)

Indexing with PyTorch is similar to index with NumPy

In [ ]:
# Create a tensor

import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middke brcket (dim=1)
x[0][0]  # "x[0, 0]" is same as "x[0][0]"

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
# challange to find number 9 from the "x" tensor
x[0][2][2]

tensor(9)

In [ ]:
# ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[0,2,1]

tensor(8)

In [ ]:
t = torch.rand(5, 3, 6, 2)
t

tensor([[[[9.3650e-01, 4.7256e-02],
          [1.9659e-01, 2.4272e-02],
          [8.3763e-01, 6.6038e-01],
          [9.1828e-01, 5.0169e-01],
          [1.8556e-01, 9.1524e-01],
          [7.6120e-02, 4.4406e-01]],

         [[9.1738e-01, 6.1814e-02],
          [8.4004e-01, 2.9585e-01],
          [1.9423e-02, 1.4711e-01],
          [7.1301e-01, 9.5757e-01],
          [4.2250e-01, 1.1947e-01],
          [3.7732e-01, 9.3229e-01]],

         [[1.6923e-01, 9.7764e-02],
          [7.7895e-01, 7.4869e-01],
          [5.3451e-01, 6.3639e-01],
          [3.1024e-01, 5.6626e-01],
          [5.7500e-01, 1.6582e-01],
          [9.2496e-01, 8.5855e-01]]],


        [[[3.1164e-01, 2.0974e-01],
          [8.2507e-01, 1.7019e-01],
          [1.3887e-01, 2.4704e-01],
          [1.2298e-01, 1.1111e-01],
          [6.2295e-01, 2.1117e-02],
          [8.3446e-01, 2.0670e-01]],

         [[3.2238e-01, 1.3072e-01],
          [1.7209e-01, 3.5187e-01],
          [5.5809e-01, 3.9483e-01],
          [6.4163e

In [ ]:
t.ndim, t.shape

(4, torch.Size([5, 3, 6, 2]))

In [ ]:
t[4]

tensor([[[0.3034, 0.1518],
         [0.8129, 0.6068],
         [0.9982, 0.9951],
         [0.7402, 0.0191],
         [0.7891, 0.5753],
         [0.1724, 0.1003]],

        [[0.6397, 0.2431],
         [0.1647, 0.3111],
         [0.8539, 0.8432],
         [0.6928, 0.1132],
         [0.5659, 0.4691],
         [0.9360, 0.3802]],

        [[0.8234, 0.0112],
         [0.8047, 0.4856],
         [0.3669, 0.1187],
         [0.7126, 0.5849],
         [0.6389, 0.8252],
         [0.7446, 0.6512]]])

In [ ]:
t.shape

torch.Size([5, 3, 6, 2])

In [ ]:
t

tensor([[[[9.3650e-01, 4.7256e-02],
          [1.9659e-01, 2.4272e-02],
          [8.3763e-01, 6.6038e-01],
          [9.1828e-01, 5.0169e-01],
          [1.8556e-01, 9.1524e-01],
          [7.6120e-02, 4.4406e-01]],

         [[9.1738e-01, 6.1814e-02],
          [8.4004e-01, 2.9585e-01],
          [1.9423e-02, 1.4711e-01],
          [7.1301e-01, 9.5757e-01],
          [4.2250e-01, 1.1947e-01],
          [3.7732e-01, 9.3229e-01]],

         [[1.6923e-01, 9.7764e-02],
          [7.7895e-01, 7.4869e-01],
          [5.3451e-01, 6.3639e-01],
          [3.1024e-01, 5.6626e-01],
          [5.7500e-01, 1.6582e-01],
          [9.2496e-01, 8.5855e-01]]],


        [[[3.1164e-01, 2.0974e-01],
          [8.2507e-01, 1.7019e-01],
          [1.3887e-01, 2.4704e-01],
          [1.2298e-01, 1.1111e-01],
          [6.2295e-01, 2.1117e-02],
          [8.3446e-01, 2.0670e-01]],

         [[3.2238e-01, 1.3072e-01],
          [1.7209e-01, 3.5187e-01],
          [5.5809e-01, 3.9483e-01],
          [6.4163e

In [ ]:
t[0]

tensor([[[0.9365, 0.0473],
         [0.1966, 0.0243],
         [0.8376, 0.6604],
         [0.9183, 0.5017],
         [0.1856, 0.9152],
         [0.0761, 0.4441]],

        [[0.9174, 0.0618],
         [0.8400, 0.2959],
         [0.0194, 0.1471],
         [0.7130, 0.9576],
         [0.4225, 0.1195],
         [0.3773, 0.9323]],

        [[0.1692, 0.0978],
         [0.7790, 0.7487],
         [0.5345, 0.6364],
         [0.3102, 0.5663],
         [0.5750, 0.1658],
         [0.9250, 0.8585]]])

In [ ]:
t[1]

tensor([[[0.3116, 0.2097],
         [0.8251, 0.1702],
         [0.1389, 0.2470],
         [0.1230, 0.1111],
         [0.6230, 0.0211],
         [0.8345, 0.2067]],

        [[0.3224, 0.1307],
         [0.1721, 0.3519],
         [0.5581, 0.3948],
         [0.6416, 0.0806],
         [0.3679, 0.1535],
         [0.0143, 0.8194]],

        [[0.3491, 0.1073],
         [0.7723, 0.6505],
         [0.0609, 0.2144],
         [0.7185, 0.8382],
         [0.3006, 0.1128],
         [0.8451, 0.0964]]])

In [ ]:
t[2]

tensor([[[0.7622, 0.1011],
         [0.1098, 0.2267],
         [0.2454, 0.4199],
         [0.3262, 0.1384],
         [0.7136, 0.0243],
         [0.5946, 0.9737]],

        [[0.9278, 0.3116],
         [0.8412, 0.7278],
         [0.6128, 0.6366],
         [0.3394, 0.9462],
         [0.5735, 0.2454],
         [0.1323, 0.2122]],

        [[0.6501, 0.2543],
         [0.9954, 0.9956],
         [0.7254, 0.8894],
         [0.2218, 0.5884],
         [0.8528, 0.8629],
         [0.5394, 0.8243]]])

In [ ]:
t[3]

tensor([[[6.5933e-01, 6.9045e-01],
         [1.0360e-01, 4.8554e-01],
         [4.0679e-01, 5.3960e-01],
         [1.4579e-01, 4.7523e-01],
         [7.9612e-01, 1.2042e-01],
         [8.7910e-02, 9.3604e-01]],

        [[4.8917e-01, 4.5719e-01],
         [9.2234e-01, 2.7849e-01],
         [2.7700e-01, 7.4138e-01],
         [8.6717e-01, 6.6624e-01],
         [1.6156e-01, 9.6692e-01],
         [7.5186e-01, 9.5977e-01]],

        [[6.6704e-04, 4.5498e-01],
         [9.4612e-01, 4.2330e-01],
         [6.1124e-01, 3.9780e-01],
         [6.6434e-01, 5.3173e-01],
         [9.8116e-01, 1.3675e-01],
         [2.5492e-01, 8.0782e-02]]])

In [ ]:
t[3][2]

tensor([[6.6704e-04, 4.5498e-01],
        [9.4612e-01, 4.2330e-01],
        [6.1124e-01, 3.9780e-01],
        [6.6434e-01, 5.3173e-01],
        [9.8116e-01, 1.3675e-01],
        [2.5492e-01, 8.0782e-02]])

In [ ]:
t[3][2][5], t[3, 2, 5]

(tensor([0.2549, 0.0808]), tensor([0.2549, 0.0808]))

In [ ]:
t[3][2][5][1], t[3, 2, 5, 1]

(tensor(0.0808), tensor(0.0808))

In [ ]:
t[:, 2, 5, 1]

tensor([0.8585, 0.0964, 0.8243, 0.0808, 0.6512])

In [ ]:
t[:3, 2, 5, 1]

tensor([0.8585, 0.0964, 0.8243])

In [ ]:
t[3:, 2, 5, 1]

tensor([0.0808, 0.6512])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and first dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
# Index on x to return `3,6,9`
x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want int PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

**learn more:** https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype # NumPy default datatype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype # torch default datatype

torch.float32

In [ ]:
# here we convert the datatype `float64` to `float32`

tensor = torch.from_numpy(array).type(torch.float32)
array, tensor, array.dtype, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 dtype('float64'),
 torch.float32)

In [ ]:
# Change the value of the `array`, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
# Change the value of the `tensor`, what will this do to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

**Learn more:** https://pytorch.org/docs/stable/notes/randomness.html

In [1]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9075, 0.5952, 0.0436, 0.3709],
        [0.1993, 0.8297, 0.6283, 0.1790],
        [0.5418, 0.7446, 0.9434, 0.4316]])
tensor([[0.3899, 0.7503, 0.9085, 0.5861],
        [0.4427, 0.3833, 0.0407, 0.4726],
        [0.2094, 0.3874, 0.1444, 0.5798]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [2]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

**Which GPU(s) to Get for Deep Learning: My Experience and Advice for Using GPUs in Deep Learning::->** https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/

In [1]:
!nvidia-smi

Wed Apr 24 17:27:46 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 1. Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

**e.g:** run on GPU if available, else default to CPU

In [4]:
# Setup device agnostic code || https://pytorch.org/docs/stable/notes/cuda.html
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count the number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is becaue using GPU results in faster computations.

In [6]:
# Create a tensor (default on the GPU)
tensor = torch.tensor([1, 2, 3], device = "cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
# even if we don't declare before
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device) # expected output device is `cpu` because we already write a condition before for the set-uping device

tensor([1, 2, 3]) cpu


In [9]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [11]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [12]:
# To fix the GPU tensor with NumPy issue, we can first get it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')