# Exercises

## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)
* The documentation on [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html)*italicized text*

In [38]:
import torch

In [39]:
# default float datatype is `float32`

default_float_datatype_tensor = torch.tensor([0.5, 0.1, 0.7, 0.3])
default_float_datatype_tensor, default_float_datatype_tensor.dtype

(tensor([0.5000, 0.1000, 0.7000, 0.3000]), torch.float32)

In [40]:
# torch.Tensor

## Data Types

# float32 datatype
# create tensor
float_32_tensor = torch.tensor([4, 7, 8], dtype=torch.float) # `torch.float` or, `torch.float32`
float_32_tensor, float_32_tensor.dtype

(tensor([4., 7., 8.]), torch.float32)

In [41]:
float_32Tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
float_32Tensor

tensor([1., 2., 3.])

In [42]:
# float64 datatype
float_64_tensor = torch.tensor([1, 4, 2], dtype=torch.float64) # `torch.float64` or, `torch.double`
float_64_tensor, float_64_tensor.dtype

(tensor([1., 4., 2.], dtype=torch.float64), torch.float64)

In [43]:
float_64Tensor = torch.tensor([6, 9, 2], dtype=torch.double)
float_64Tensor, float_64Tensor.dtype

(tensor([6., 9., 2.], dtype=torch.float64), torch.float64)

In [44]:
'''
1. Sometimes referred to as binary16: uses 1 sign, 5 exponent, and 10 significand bits. Useful when precision is important at the expense of range.
'''

# 1. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.float16), torch.float16)

In [45]:
#
float_16Tensor = torch.tensor([8, 2, 6], dtype=torch.half)
float_16Tensor, float_16Tensor.dtype

(tensor([8., 2., 6.], dtype=torch.float16), torch.float16)

In [46]:
'''
Sometimes referred to as Brain Floating Point: uses 1 sign, 8 exponent, and 7 significand bits. Useful when range is important, since it has the same number of exponent bits as float32
'''

# 2. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.bfloat16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.bfloat16), torch.bfloat16)

In [47]:
# default integer datatype is `int64`
default_int_datatype_tensor = torch.tensor([6,1,9])
default_int_datatype_tensor, default_int_datatype_tensor.dtype

(tensor([6, 1, 9]), torch.int64)

In [48]:
# integers(signed) datatypes
int_8_tensor = torch.tensor([4,8,1], dtype=torch.int8)
int_8_tensor, int_8_tensor.dtype

(tensor([4, 8, 1], dtype=torch.int8), torch.int8)

In [49]:
int_16_tensor = torch.tensor([6,8,2], dtype=torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([6, 8, 2], dtype=torch.int16), torch.int16)

In [50]:
int_16_or_short_tensor = torch.tensor([7,1,9], dtype=torch.short)
int_16_or_short_tensor, int_16_or_short_tensor.dtype

(tensor([7, 1, 9], dtype=torch.int16), torch.int16)

In [51]:
# 32bit integers (signed)
int_32_tensor = torch.tensor([6,3,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([6, 3, 9], dtype=torch.int32), torch.int32)

In [52]:
int32Tensor = torch.tensor([6,1,9], dtype=torch.int)
int32Tensor, int32Tensor.dtype

(tensor([6, 1, 9], dtype=torch.int32), torch.int32)

In [53]:
int_64_Tensor = torch.tensor([7,1,8], dtype=torch.int64)
int_64_Tensor, int_64_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [54]:
int_64_or_long_Tensor = torch.tensor([7,1,8], dtype=torch.long)
int_64_or_long_Tensor, int_64_or_long_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [55]:
# boolean datatype
boolean_tensor = torch.tensor([1,0,1,0,1], dtype=torch.bool)
boolean_tensor, boolean_tensor.dtype

(tensor([ True, False,  True, False,  True]), torch.bool)

In [57]:
## backward compatibility
# 32-bit floating point
x = torch.FloatTensor([1,8,5])
x, x.dtype

(tensor([1., 8., 5.]), torch.float32)

In [60]:
# converting datatype (float32 to float64)

# 1.
y = x.type(torch.DoubleTensor)
y, y.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [62]:
# 2.
z = x.type(torch.float64)
z, z.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [63]:
# 3.
w = x.type(torch.double)
w, w.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [64]:
# 64-bit floating point
a = torch.DoubleTensor([7,1,5,4])
a

tensor([7., 1., 5., 4.], dtype=torch.float64)

In [65]:
# 16-bit floating point
b = torch.HalfTensor([4,7,1])
b

tensor([4., 7., 1.], dtype=torch.float16)

In [66]:
# 16-bit floating point
c = torch.BFloat16Tensor([5,8,4])
c

tensor([5., 8., 4.], dtype=torch.bfloat16)

In [69]:
# 8-bit integer (unsigned)
d = torch.ByteTensor([1,2,3])
d

tensor([1, 2, 3], dtype=torch.uint8)

In [70]:
# 8-bit integer (signed)
e = torch.CharTensor([3,5,4])
e

tensor([3, 5, 4], dtype=torch.int8)

In [71]:
# 16-bit integer (signed)
f = torch.ShortTensor([5,7,9])
f

tensor([5, 7, 9], dtype=torch.int16)

In [72]:
# 32-bit integer (signed)
g = torch.IntTensor([6,1,5])
g

tensor([6, 1, 5], dtype=torch.int32)

In [74]:
# 64-bit integer (signed)
h = torch.LongTensor([5,2,9])
h

tensor([5, 2, 9])

In [77]:
# Boolean
i = torch.BoolTensor([0,1,0])
i, i.dtype

(tensor([False,  True, False]), torch.bool)

In [80]:
# factory function - `torch.empty()`
k = torch.empty(size=(3,3),dtype=torch.float16)
k, k.ndim, k.shape

(tensor([[ 1.2112e-04, -2.4605e-04,  2.7050e+02],
         [ 0.0000e+00,         nan, -2.4152e-04],
         [ 2.7050e+02,  0.0000e+00,  4.7684e-06]], dtype=torch.float16),
 2,
 torch.Size([3, 3]))