### PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# number of dimension : https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html

scalar.ndim

0

In [4]:
# Get tensor back as Python int

scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[2,4],
                       [1,3]])
MATRIX

tensor([[2, 4],
        [1, 3]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([2, 4])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,3,9],
                        [2,4,6],
                        [5,9,7]]])
TENSOR

tensor([[[1, 3, 9],
         [2, 4, 6],
         [5, 9, 7]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 3, 9],
        [2, 4, 6],
        [5, 9, 7]])

In [16]:
MY_TENSOR = torch.tensor([[[
                              [1,3,9,4], # <0
                              [2,4,8,6], # <1
#                              [4,1,6,3]  # <2
#                              ^ ^ ^ ^
#                              0 1 2 3
                            ]]])
MY_TENSOR

tensor([[[[1, 3, 9, 4],
          [2, 4, 8, 6]]]])

In [17]:
MY_TENSOR.ndim

4

In [18]:
MY_TENSOR.shape

torch.Size([1, 1, 2, 4])

## Tensor Exercise

In [19]:
TENSOR = torch.tensor([[1,2,3], [4,5,6]])
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
TENSOR.ndim

2

In [21]:
TENSOR.shape

torch.Size([2, 3])

In [22]:
TENSOR[0]

tensor([1, 2, 3])

In [23]:
TENSOR2 = torch.tensor([
    [2,1,4],
    [1,5,2]
])
TENSOR2

tensor([[2, 1, 4],
        [1, 5, 2]])

In [24]:
TENSOR2.ndim

2

In [25]:
TENSOR2.shape

torch.Size([2, 3])

In [26]:
TENSOR3 = torch.tensor([
    [2,1,4],
    [1,5,2],
    [7,5,9]
])
TENSOR3

tensor([[2, 1, 4],
        [1, 5, 2],
        [7, 5, 9]])

In [27]:
TENSOR3.ndim

2

In [28]:
TENSOR3.shape

torch.Size([3, 3])

In [29]:
TENSOR4 = torch.tensor([[
    [1,2,3,2],
    [7,8,9,7],
    [4,5,6,9]
]])

TENSOR4

tensor([[[1, 2, 3, 2],
         [7, 8, 9, 7],
         [4, 5, 6, 9]]])

In [30]:
TENSOR4.ndim

3

In [31]:
TENSOR4.shape

torch.Size([1, 3, 4])

In [32]:
TENSOR5 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ]
                ]
            ]
        ]
    ]
)

TENSOR5

tensor([[[[[[1, 2],
            [4, 1],
            [6, 8]]]]]])

In [33]:
TENSOR5.ndim # expected 6

6

In [34]:
TENSOR5.shape #expected tensor.Size([1,1,1,1,3,2])

torch.Size([1, 1, 1, 1, 3, 2])

In [35]:
TENSOR6 = torch.tensor(
    [
            [
              [1,2],
              [4,8],
              [3,9]
            ],
            [
              [5,6],
              [7,9],
              [4,1]
            ]

    ]
)

TENSOR6

tensor([[[1, 2],
         [4, 8],
         [3, 9]],

        [[5, 6],
         [7, 9],
         [4, 1]]])

In [36]:
TENSOR6.ndim

3

In [37]:
TENSOR6.shape

torch.Size([2, 3, 2])

In [38]:
TENSOR7 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ],
                [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ]
    ]
)
TENSOR7

tensor([[[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]],



         [[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]]],




        [[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
      

In [39]:
TENSOR7.ndim

6

In [40]:
TENSOR7.shape

torch.Size([2, 2, 3, 2, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html

In [41]:
# Create a random tensors of size (3,4)
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.3980, 0.4239, 0.8798, 0.1262],
        [0.0276, 0.7187, 0.1541, 0.5594],
        [0.8143, 0.8739, 0.2233, 0.0370]])

In [42]:
random_tensors.ndim

2

In [43]:
random_tensors = torch.rand(10, 8)
random_tensors

tensor([[0.8486, 0.4427, 0.7499, 0.8772, 0.2830, 0.2582, 0.7048, 0.5277],
        [0.2161, 0.9272, 0.1830, 0.9218, 0.7176, 0.7243, 0.1703, 0.0811],
        [0.6426, 0.6285, 0.6602, 0.0439, 0.3292, 0.4195, 0.2584, 0.8867],
        [0.1175, 0.2654, 0.5575, 0.9663, 0.4819, 0.8141, 0.8345, 0.4044],
        [0.5008, 0.8806, 0.0701, 0.7548, 0.0468, 0.9994, 0.4426, 0.7595],
        [0.4596, 0.1954, 0.1341, 0.1639, 0.5018, 0.6965, 0.4045, 0.8622],
        [0.1646, 0.4733, 0.4366, 0.1257, 0.7250, 0.3032, 0.3774, 0.7556],
        [0.3627, 0.1571, 0.3575, 0.3806, 0.8200, 0.9910, 0.1003, 0.0684],
        [0.7358, 0.2734, 0.4987, 0.4126, 0.9875, 0.0315, 0.9085, 0.5416],
        [0.3998, 0.6831, 0.4645, 0.1273, 0.1348, 0.3573, 0.4280, 0.6441]])

In [44]:
random_tensors.ndim

2

In [45]:
random_tensors = torch.rand(10, 100, 100)
random_tensors

tensor([[[0.8615, 0.3941, 0.3823,  ..., 0.9119, 0.6847, 0.6665],
         [0.1381, 0.1364, 0.4550,  ..., 0.9552, 0.3661, 0.1031],
         [0.7679, 0.3438, 0.0920,  ..., 0.8891, 0.8903, 0.2773],
         ...,
         [0.5055, 0.9890, 0.7642,  ..., 0.2358, 0.0015, 0.3437],
         [0.1083, 0.9774, 0.5353,  ..., 0.3224, 0.8465, 0.0693],
         [0.3478, 0.7690, 0.2616,  ..., 0.6296, 0.8021, 0.3728]],

        [[0.9389, 0.8540, 0.5579,  ..., 0.1549, 0.2098, 0.6464],
         [0.7973, 0.5627, 0.5484,  ..., 0.1269, 0.4680, 0.6601],
         [0.0863, 0.6145, 0.4686,  ..., 0.7213, 0.0275, 0.3794],
         ...,
         [0.8671, 0.3460, 0.1915,  ..., 0.0416, 0.4751, 0.8153],
         [0.7456, 0.4116, 0.9780,  ..., 0.9129, 0.5709, 0.8716],
         [0.1466, 0.2600, 0.2280,  ..., 0.0596, 0.7533, 0.3664]],

        [[0.6164, 0.0175, 0.7527,  ..., 0.5516, 0.8359, 0.8202],
         [0.0136, 0.5827, 0.1353,  ..., 0.6051, 0.7378, 0.1476],
         [0.5453, 0.8496, 0.0704,  ..., 0.8728, 0.6590, 0.

In [46]:
random_tensors.ndim

3

In [47]:
random_tensors = torch.rand(10, 10, 10, 10, 10)
random_tensors

tensor([[[[[7.8713e-01, 7.0592e-01, 6.6335e-01,  ..., 7.4781e-01,
            2.3085e-01, 9.7530e-01],
           [1.9149e-01, 2.1270e-01, 5.5962e-01,  ..., 3.6457e-02,
            8.3087e-01, 3.8929e-01],
           [7.5259e-02, 9.6909e-01, 9.8508e-01,  ..., 1.0773e-01,
            9.6112e-01, 1.8001e-01],
           ...,
           [7.2984e-02, 2.0294e-01, 3.7653e-01,  ..., 2.5808e-01,
            5.2310e-01, 8.0133e-01],
           [8.4776e-01, 8.4164e-01, 8.0060e-01,  ..., 5.8560e-01,
            9.1022e-01, 7.0066e-01],
           [8.9430e-01, 4.7159e-01, 1.1112e-01,  ..., 2.8204e-01,
            5.9588e-01, 9.7665e-01]],

          [[9.4862e-02, 9.2219e-01, 3.9637e-01,  ..., 3.7941e-01,
            1.0737e-01, 1.7474e-02],
           [4.5580e-01, 4.3354e-01, 8.4047e-01,  ..., 7.1270e-01,
            1.0816e-01, 7.3492e-01],
           [8.1909e-01, 9.8774e-01, 4.3536e-01,  ..., 2.6742e-01,
            1.3818e-01, 1.6749e-01],
           ...,
           [6.6402e-01, 8.4345e-01, 8.3

In [48]:
random_tensors.ndim

5

In [49]:
random_tensors.shape

torch.Size([10, 10, 10, 10, 10])

In [50]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [51]:
itensor = torch.rand(224, 224, 3)
itensor

tensor([[[0.0907, 0.6568, 0.5638],
         [0.2816, 0.8972, 0.3471],
         [0.4042, 0.7537, 0.2872],
         ...,
         [0.3333, 0.9495, 0.8644],
         [0.8002, 0.4159, 0.2909],
         [0.1575, 0.5983, 0.1456]],

        [[0.4585, 0.2761, 0.6516],
         [0.4288, 0.9434, 0.5385],
         [0.9288, 0.2986, 0.0139],
         ...,
         [0.3081, 0.4831, 0.3364],
         [0.3479, 0.0947, 0.0724],
         [0.2593, 0.8711, 0.4381]],

        [[0.4015, 0.9406, 0.7896],
         [0.7252, 0.1112, 0.7116],
         [0.3605, 0.1408, 0.6893],
         ...,
         [0.0649, 0.6437, 0.5865],
         [0.0803, 0.9508, 0.3066],
         [0.4515, 0.5594, 0.9088]],

        ...,

        [[0.7319, 0.2389, 0.1280],
         [0.4612, 0.4715, 0.7338],
         [0.0707, 0.4331, 0.5252],
         ...,
         [0.5281, 0.5977, 0.1624],
         [0.0810, 0.3393, 0.1224],
         [0.0677, 0.8395, 0.7109]],

        [[0.4396, 0.4912, 0.4742],
         [0.3414, 0.5318, 0.7630],
         [0.

In [52]:
itensor.ndim

3

## Zeros and ones

In [53]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
new_random_tensor = torch.rand(3,4)
new_random_tensor

tensor([[0.7845, 0.5659, 0.8578, 0.0404],
        [0.1606, 0.6115, 0.1250, 0.1651],
        [0.0669, 0.5667, 0.9243, 0.8209]])

In [55]:
zeros * new_random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

`torch.arange()` : https://pytorch.org/docs/stable/generated/torch.arange.html

In [58]:
# Use torch.range(1,11)
# Depreciated message:::>>>> UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
zero_to_hundred = torch.arange(start=0, end=100, step=10)
zero_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
# Creating tensors like
# when we have to define a tensor shape from a pre-defined tensor and overwrite with zeros
new_tensor_from_zero_to_hundred_tensor = torch.zeros_like(input=zero_to_hundred)
new_tensor_from_zero_to_hundred_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

**Note:** Tensor datatypes is one the 3 big errors you'll run into with PyTorch && Deep Learning:

1.   Tensors not right datatype
2.   Tensors not right shape
3.   Tensors not on the right device


Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)



In [61]:
# default tensor datatype - default tensor datatype is depends on input input of the given tensor

# here i will set `int` numbers for the tensor, so the default datatype of the tensor will be `int64`
# so the default is `int64` for int numbers
default_datatype_tensor = torch.tensor([5,8,1,6,2,9])

default_datatype_tensor

tensor([5, 8, 1, 6, 2, 9])

In [62]:
default_datatype_tensor.dtype

torch.int64

In [63]:
# here i will set `float` numbers for the tensor, so the default datatype would be `float32`
# so the default is `float32` for int numbers
default_datatype_tensor = torch.tensor([3.1,4.9,6.4,.5])

default_datatype_tensor

tensor([3.1000, 4.9000, 6.4000, 0.5000])

In [64]:
default_datatype_tensor.dtype

torch.float32

In [65]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 2.0, 4.0], dtype=torch.float32) # defined `float32`

float_32_tensor

tensor([3., 2., 4.])

In [66]:
float_32_tensor.dtype

torch.float32

In [67]:
# set float numbers but later define the datatype your want to sent with the tensor
int64_tensor = torch.tensor([4.1,2,4,7], dtype=torch.int64)
int64_tensor

tensor([4, 2, 4, 7])

In [68]:
int64_tensor.dtype

torch.int64

In [69]:
#
float_32_tensor = torch.tensor([7.3,1,9,4.2], dtype=None # what datatype is the tensor (e.g. float32. float16)
                                                        )
float_32_tensor

tensor([7.3000, 1.0000, 9.0000, 4.2000])

In [70]:
float_32_tensor.dtype

torch.float32

In [71]:
# with more parameters
float_32_tensor = torch.tensor([4.1,7.5,7.8],
                               dtype = None, # set  datatypes:  e.g. float16, float32 :> available datatypes: https://pytorch.org/docs/stable/tensors.html || https://en.wikipedia.org/wiki/Precision_(computer_science)
                               device = None, # what device is your tensor on e.g. 'cpu' or 'cuda' mean gpu
                               requires_grad = False # whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([4.1000, 7.5000, 7.8000])

In [72]:
# converted the datatype 'float_32' to 'float_16' of a tensor

# how might we change the datatype of the tensor
float16_tensor = float_32_tensor.type(torch.float16)
float16_tensor

tensor([4.1016, 7.5000, 7.8008], dtype=torch.float16)

# Excercise (DataTypes)

In [73]:
# boolean data types
boolean_tensor = torch.tensor([1,0,0,1,0,1,1], dtype=torch.bool)

boolean_tensor

tensor([ True, False, False,  True, False,  True,  True])

In [74]:
boolean_tensor.dtype

torch.bool

In [75]:
# requires_grad = True
MY_TENSOR = torch.tensor([[1.1, 9.3], [3.6, 6.7]], requires_grad=True)

OUT = MY_TENSOR.pow(2).sum()
OUT.backward()
MY_TENSOR.grad

tensor([[ 2.2000, 18.6000],
        [ 7.2000, 13.4000]])

## Tensor Views
PyTorch allows a tensor to be a `View` of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting `View` avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

For example, to get a view of an existing tensor `first_tensor`, you can call `t.view(...)`.


**Source:** https://pytorch.org/docs/stable/tensor_view.html#tensor-view-doc

In [76]:
# example
first_tensor = torch.rand(4,4)
first_tensor

tensor([[0.8288, 0.8244, 0.7798, 0.3600],
        [0.3897, 0.0223, 0.1867, 0.8538],
        [0.9242, 0.3062, 0.0779, 0.0690],
        [0.2537, 0.5320, 0.7521, 0.1124]])

In [77]:
second_tensor = first_tensor.view(2,8)
second_tensor

tensor([[0.8288, 0.8244, 0.7798, 0.3600, 0.3897, 0.0223, 0.1867, 0.8538],
        [0.9242, 0.3062, 0.0779, 0.0690, 0.2537, 0.5320, 0.7521, 0.1124]])

In [78]:
# check if the two tensors sharing the same data

# using `first_tensor.storage()` you will get deprecated message, To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
first_tensor.untyped_storage().data_ptr() == second_tensor.untyped_storage().data_ptr() # `first_tensor` and `second_tensor` share the same underlying data

True

In [79]:
# Modifying view tensor(e.g.`second_tensor`) changes base tensor(e.g. `first_tensor`) as well

# first extract value of given indices
second_tensor[0][0]

# updating value
second_tensor[0][0] = 0.401

# check whether the value of the first_tensor is updated or not
first_tensor[0][0]

# print the whole tensor
first_tensor

#    Note:** Since views share underlying data with its base tensor, if you edit the data in the view, it will be reflected in the base tensor as well.



tensor([[0.4010, 0.8244, 0.7798, 0.3600],
        [0.3897, 0.0223, 0.1867, 0.8538],
        [0.9242, 0.3062, 0.0779, 0.0690],
        [0.2537, 0.5320, 0.7521, 0.1124]])

Typically a PyTorch op returns a new tensor as output, e.g. `add()`. But in case of view ops, outputs are views of input tensors to avoid unnecessary data copy. No data movement occurs when creating a view, view tensor just changes the way it interprets the same data. Taking a view of contiguous tensor could potentially produce a non-contiguous tensor. Users should pay additional attention as contiguity might have implicit performance impact. `transpose()` is a common example.

**Source:** https://pytorch.org/docs/stable/tensor_view.html#tensor-views

In [80]:
first_tensor.is_contiguous()

True

In [81]:
second_tensor.is_contiguous()

True

In [82]:
# create new base tensor
base_tensor = torch.tensor([[0,1],[2,3]])
print(base_tensor.is_contiguous())
base_tensor

True


tensor([[0, 1],
        [2, 3]])

In [83]:
view_tensor = base_tensor.transpose(0,1) # `view_tensor` if a view of `base_tensor`. No data movement happened here
view_tensor

tensor([[0, 2],
        [1, 3]])

In [84]:
# `view_tensor`(transpose) might be non-contiguous
# so, let's check whether it's right or not
view_tensor.is_contiguous()

False

In [85]:
# To get contiguous tensor, call `.contiguous()` to enfore
# copying data when `view_tensor` is not contiguous
copy_tensor = view_tensor.contiguous()
copy_tensor

# check now, if `copy_tensor` is contiguous or not
copy_tensor.is_contiguous()

True

## Arithmetic Operations

In [86]:
# multiplication with two different datatypes or with same datatype but different bits(e.g. 16 or 32 or 64)

float_16_tensor = torch.tensor([1.1,5.3,6.9], dtype=torch.float16)

float_16_tensor

tensor([1.0996, 5.3008, 6.8984], dtype=torch.float16)

In [87]:
flotat_32_tensor = torch.tensor([4.7, 4.1,8.3], dtype=torch.float32)

float_32_tensor

tensor([4.1000, 7.5000, 7.8000])

In [88]:
float_16_tensor * float_32_tensor

tensor([ 4.5084, 39.7559, 53.8078])

In [89]:
int_32_tensor = torch.tensor([5,8,3], dtype=torch.int32)
int_32_tensor

tensor([5, 8, 3], dtype=torch.int32)

In [90]:
int_32_tensor * float_32_tensor

tensor([20.5000, 60.0000, 23.4000])

In [91]:
int_64_tensor = torch.tensor([2,7,9], dtype=torch.int64)
int_64_tensor

tensor([2, 7, 9])

In [92]:
float_32_tensor * int_64_tensor

tensor([ 8.2000, 52.5000, 70.2000])

In [93]:
long_tensor = torch.tensor([4,6,9], dtype=torch.long)
long_tensor

tensor([4, 6, 9])

In [94]:
long_tensor * float_32_tensor

tensor([16.4000, 45.0000, 70.2000])

## Getting information from tensors (tensor attributes)
1.   Tensors not right datatype - to do that get datatype from a tensor, can use `tensor.dtype`
2.   Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3.   Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [95]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2009, 0.5151, 0.2612, 0.1550],
        [0.2848, 0.8256, 0.8993, 0.4195],
        [0.3407, 0.4270, 0.9725, 0.6145]])

In [96]:
# Find out details anout some tensor
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # there are two way to get shape or size of a tensor, 1. with attribute (e.g. some_tensor.shape) 2. with function (e.g. some_tensor.size())
print(f"Device of tensor is on: {some_tensor.device}")

tensor([[0.2009, 0.5151, 0.2612, 0.1550],
        [0.2848, 0.8256, 0.8993, 0.4195],
        [0.3407, 0.4270, 0.9725, 0.6145]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


In [97]:
check = torch.rand(3,4)
check

tensor([[0.5627, 0.2912, 0.3800, 0.2034],
        [0.2308, 0.3525, 0.0540, 0.7613],
        [0.7178, 0.1026, 0.0010, 0.2779]])

In [98]:
check.dtype


torch.float32

In [99]:
deck = check.type(torch.float16)
deck.dtype

torch.float16

In [100]:
deck

tensor([[0.5625, 0.2913, 0.3799, 0.2034],
        [0.2307, 0.3525, 0.0540, 0.7612],
        [0.7178, 0.1026, 0.0010, 0.2778]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [101]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [102]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [103]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [104]:
tensor

tensor([1, 2, 3])

In [105]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [106]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication (Part #1)

Two main ways of performing multiplication in neural networks and deep learning.

1. Element-wise Multiplication
2. Matrix Multiplication (dot prouct)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html#

In [107]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [108]:
# Matrix Multiplication by torch
torch.matmul(tensor, tensor)

tensor(14)

In [109]:
# Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14

In [110]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[0] * tensor[0]
print(value)

tensor(3)
CPU times: user 2.04 ms, sys: 0 ns, total: 2.04 ms
Wall time: 2.69 ms


In [111]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.55 ms, sys: 0 ns, total: 1.55 ms
Wall time: 1.55 ms


tensor(14)

### Matrix Multiplication (Part #2)

There are two main rules that performing matrix multiplication needs to stisfy:
1.  The **inner dimensions** must match:
    *   `(3,2) @ (3,2)` won't work
    *   `(2,3) @ (3,2)` will work
    *   `(3,2) @ (2,3)` will work

    ***Note:*** `@` is a attribute in tensor for multiplying two tensor whereas `tensor.matmul()` is a function. e.g. `tensor1 @ tensor2` `==` `torch.matmul(tensor1, tensor2)`
2.  The resulting matrix has the shape of the **outer dimensions**:
    *   `(2,3) @ (3,2)` -> `(2,2)`
    *   `(3,2) @ (2,3)` -> `(3,3)`

#### One of the main errors in matrix multiplication is shape error

In [112]:
torch.matmul(torch.rand(3,2), torch.rand(3,2)) # error occurs

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [113]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.9909, 1.1400],
        [1.4230, 1.6111]])

In [114]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.4394, 0.7058, 0.8775],
        [0.5524, 0.6247, 0.4361],
        [0.1790, 0.4546, 0.7818]])

In [115]:
torch.matmul(torch.rand(4,5), torch.rand(5,4))

tensor([[2.3516, 2.0984, 1.3676, 2.2717],
        [1.7823, 1.5090, 1.1456, 1.9227],
        [2.0045, 1.9583, 1.6695, 2.3025],
        [1.1770, 1.1576, 0.7166, 1.1965]])

In [116]:
torch.matmul(torch.rand(10,4), torch.rand(4, 5))

tensor([[0.5331, 1.2154, 0.6247, 0.7963, 0.9759],
        [0.5268, 0.7716, 0.4764, 0.5412, 0.5834],
        [1.0640, 1.0023, 0.5733, 1.1218, 0.7762],
        [1.3438, 1.5001, 0.8166, 1.4390, 1.1953],
        [1.1888, 1.3167, 0.6909, 1.2899, 1.0646],
        [0.7675, 0.9701, 0.5974, 0.7177, 0.7434],
        [1.4124, 1.2817, 0.7172, 1.4108, 1.0154],
        [0.7440, 0.9593, 0.4195, 0.9219, 0.8214],
        [1.2561, 1.0827, 0.5976, 1.2190, 0.8682],
        [0.5789, 1.0156, 0.5294, 0.6479, 0.8321]])

In [117]:
# if inner dimension match but different outer dimension
torch.matmul(torch.rand(10,4), torch.rand(4, 6))

tensor([[0.8289, 0.9869, 0.9304, 0.9652, 1.2316, 0.8252],
        [0.5803, 0.5668, 0.5514, 0.7605, 1.1493, 0.1257],
        [0.8917, 0.9853, 0.8449, 0.9581, 1.2960, 0.8404],
        [0.7474, 0.9320, 0.8843, 1.0086, 1.4502, 0.5402],
        [0.6276, 0.7377, 0.6709, 0.7707, 1.0882, 0.5014],
        [1.0242, 0.8981, 1.0540, 0.8817, 0.5495, 1.1060],
        [1.4524, 1.3321, 1.6413, 1.4869, 1.2348, 1.2392],
        [0.5542, 0.6373, 0.6809, 0.7108, 0.8855, 0.4077],
        [1.0262, 0.8278, 0.8589, 1.0396, 1.2380, 0.5272],
        [1.5070, 1.4537, 1.7646, 1.5733, 1.3254, 1.3759]])

### One of the most common errors in deep learning: shape errors

### Matrix Multiplication (Part #3: Dealing with tensor shape errors)


In [118]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's as an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [119]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using **transpose**.

**Note:** A **transpose** switches the axes or dimensions of a given tensor

In [120]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [121]:
tensor_B.t() # transpose via function

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [122]:
tensor_B.T, tensor_B.T.shape #tranpose via attribute

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [123]:
# second approach to make transpose through function
torch.transpose(tensor_B, 0, 1) # reference:: https://pytorch.org/docs/stable/generated/torch.transpose.html

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [124]:
# The matrix multiplication operation works when tensorB is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print(f"Output: \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggregation)

In [129]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [126]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [127]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [137]:
# Find the mean **note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [138]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max of tensors

In [152]:
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [153]:
# Find the position in tensor that has the minimum value with `argmin()` -> returns index position of target tensor where the minimum value occurs.
x.argmin()

tensor(0)

In [154]:
# check the value of the position
print(f"x.argmin().item() = {x.argmin().item()}\n")
x[x.argmin().item()]

x.argmin().item() = 0



tensor(1)

In [155]:
# Find the position in tensor that has the maximum value with `argmax()`
x.argmax()

tensor(9)

In [156]:
# check the value of the position
print(f"x.armax().item() = {x.argmax().item()}\n")
x[x.argmax().item()]

x.armax().item() = 9



tensor(91)