# Exercises

## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)
* The documentation on [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html)

In [ ]:
import torch

In [ ]:
# default float datatype is `float32`

default_float_datatype_tensor = torch.tensor([0.5, 0.1, 0.7, 0.3])
default_float_datatype_tensor, default_float_datatype_tensor.dtype

(tensor([0.5000, 0.1000, 0.7000, 0.3000]), torch.float32)

In [ ]:
# torch.Tensor

## Data Types

# float32 datatype
# create tensor
float_32_tensor = torch.tensor([4, 7, 8], dtype=torch.float) # `torch.float` or, `torch.float32`
float_32_tensor, float_32_tensor.dtype

(tensor([4., 7., 8.]), torch.float32)

In [ ]:
float_32Tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
float_32Tensor

tensor([1., 2., 3.])

In [ ]:
# float64 datatype
float_64_tensor = torch.tensor([1, 4, 2], dtype=torch.float64) # `torch.float64` or, `torch.double`
float_64_tensor, float_64_tensor.dtype

(tensor([1., 4., 2.], dtype=torch.float64), torch.float64)

In [ ]:
float_64Tensor = torch.tensor([6, 9, 2], dtype=torch.double)
float_64Tensor, float_64Tensor.dtype

(tensor([6., 9., 2.], dtype=torch.float64), torch.float64)

In [ ]:
'''
1. Sometimes referred to as binary16: uses 1 sign, 5 exponent, and 10 significand bits. Useful when precision is important at the expense of range.
'''

# 1. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.float16), torch.float16)

In [ ]:
#
float_16Tensor = torch.tensor([8, 2, 6], dtype=torch.half)
float_16Tensor, float_16Tensor.dtype

(tensor([8., 2., 6.], dtype=torch.float16), torch.float16)

In [ ]:
'''
Sometimes referred to as Brain Floating Point: uses 1 sign, 8 exponent, and 7 significand bits. Useful when range is important, since it has the same number of exponent bits as float32
'''

# 2. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.bfloat16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.bfloat16), torch.bfloat16)

In [ ]:
# default integer datatype is `int64`
default_int_datatype_tensor = torch.tensor([6,1,9])
default_int_datatype_tensor, default_int_datatype_tensor.dtype

(tensor([6, 1, 9]), torch.int64)

In [ ]:
# integers(signed) datatypes
int_8_tensor = torch.tensor([4,8,1], dtype=torch.int8)
int_8_tensor, int_8_tensor.dtype

(tensor([4, 8, 1], dtype=torch.int8), torch.int8)

In [ ]:
int_16_tensor = torch.tensor([6,8,2], dtype=torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([6, 8, 2], dtype=torch.int16), torch.int16)

In [ ]:
int_16_or_short_tensor = torch.tensor([7,1,9], dtype=torch.short)
int_16_or_short_tensor, int_16_or_short_tensor.dtype

(tensor([7, 1, 9], dtype=torch.int16), torch.int16)

In [ ]:
# 32bit integers (signed)
int_32_tensor = torch.tensor([6,3,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([6, 3, 9], dtype=torch.int32), torch.int32)

In [ ]:
int32Tensor = torch.tensor([6,1,9], dtype=torch.int)
int32Tensor, int32Tensor.dtype

(tensor([6, 1, 9], dtype=torch.int32), torch.int32)

In [ ]:
int_64_Tensor = torch.tensor([7,1,8], dtype=torch.int64)
int_64_Tensor, int_64_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [ ]:
int_64_or_long_Tensor = torch.tensor([7,1,8], dtype=torch.long)
int_64_or_long_Tensor, int_64_or_long_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [ ]:
# boolean datatype
boolean_tensor = torch.tensor([1,0,1,0,1], dtype=torch.bool)
boolean_tensor, boolean_tensor.dtype

(tensor([ True, False,  True, False,  True]), torch.bool)

In [ ]:
## backward compatibility
# 32-bit floating point
x = torch.FloatTensor([1,8,5])
x, x.dtype

(tensor([1., 8., 5.]), torch.float32)

In [ ]:
# converting datatype (float32 to float64)

# 1.
y = x.type(torch.DoubleTensor)
y, y.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [ ]:
# 2.
z = x.type(torch.float64)
z, z.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [ ]:
# 3.
w = x.type(torch.double)
w, w.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [ ]:
# 64-bit floating point
a = torch.DoubleTensor([7,1,5,4])
a

tensor([7., 1., 5., 4.], dtype=torch.float64)

In [ ]:
# 16-bit floating point
b = torch.HalfTensor([4,7,1])
b

tensor([4., 7., 1.], dtype=torch.float16)

In [ ]:
# 16-bit floating point
c = torch.BFloat16Tensor([5,8,4])
c

tensor([5., 8., 4.], dtype=torch.bfloat16)

In [ ]:
# 8-bit integer (unsigned)
d = torch.ByteTensor([1,2,3])
d

tensor([1, 2, 3], dtype=torch.uint8)

In [ ]:
# 8-bit integer (signed)
e = torch.CharTensor([3,5,4])
e

tensor([3, 5, 4], dtype=torch.int8)

In [ ]:
# 16-bit integer (signed)
f = torch.ShortTensor([5,7,9])
f

tensor([5, 7, 9], dtype=torch.int16)

In [ ]:
# 32-bit integer (signed)
g = torch.IntTensor([6,1,5])
g

tensor([6, 1, 5], dtype=torch.int32)

In [ ]:
# 64-bit integer (signed)
h = torch.LongTensor([5,2,9])
h

tensor([5, 2, 9])

In [ ]:
# Boolean
i = torch.BoolTensor([0,1,0])
i, i.dtype

(tensor([False,  True, False]), torch.bool)

In [ ]:
# factory function - `torch.empty()`
k = torch.empty(size=(3,3),dtype=torch.float16)
k, k.ndim, k.shape

(tensor([[2.1667e-03, 3.7188e+01, 2.4175e+02],
         [0.0000e+00, 2.3750e+01, 3.7188e+01],
         [2.4175e+02, 0.0000e+00, 1.1921e-07]], dtype=torch.float16),
 2,
 torch.Size([3, 3]))

In [ ]:
# initializing and basic operations
m = torch.tensor([
    [1., -1.],
    [1., -1.]
])
m

tensor([[ 1., -1.],
        [ 1., -1.]])

In [ ]:
import numpy as np

from_numpy = torch.tensor(
    np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])
)
from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
check = torch.tensor([1, 2, 3], dtype=torch.float16)
check.requires_grad_()

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [ ]:
# another method
check2 = torch.tensor([1.0, 4.1, 9.2])
check2.detach_(), check2.dtype

(tensor([1.0000, 4.1000, 9.2000]), torch.float32)

In [ ]:
y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
y

<ipython-input-37-94b980d24cc2>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


tensor([1.0000, 4.1000, 9.2000])

In [ ]:
#
TENSOR_X = torch.tensor([2.1, 6.4, 3.9], requires_grad=True)

TENSOR_Y = TENSOR_X.detach()

TENSOR_Y.requires_grad_()

tensor([2.1000, 6.4000, 3.9000], requires_grad=True)