### PyTorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# number of dimension : https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html

scalar.ndim

0

In [4]:
# Get tensor back as Python int

scalar.item()

7

In [11]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[2,4],
                       [1,3]])
MATRIX

tensor([[2, 4],
        [1, 3]])

In [15]:
MATRIX.ndim

2

In [16]:
MATRIX[0]

tensor([2, 4])

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
# Tensor
TENSOR = torch.tensor([[[1,3,9],
                        [2,4,6],
                        [5,9,7]]])
TENSOR

tensor([[[1, 3, 9],
         [2, 4, 6],
         [5, 9, 7]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 3, 9],
        [2, 4, 6],
        [5, 9, 7]])

In [34]:
MY_TENSOR = torch.tensor([[[
                              [1,3,9,4], # <0
                              [2,4,8,6], # <1
#                              [4,1,6,3]  # <2
#                              ^ ^ ^ ^
#                              0 1 2 3
                            ]]])
MY_TENSOR

tensor([[[[1, 3, 9, 4],
          [2, 4, 8, 6]]]])

In [35]:
MY_TENSOR.ndim

4

In [36]:
MY_TENSOR.shape

torch.Size([1, 1, 2, 4])