### PyTorch Fundamentals

In [53]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [54]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [55]:
# number of dimension : https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html

scalar.ndim

0

In [56]:
# Get tensor back as Python int

scalar.item()

7

In [57]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [58]:
vector.ndim

1

In [59]:
vector.shape

torch.Size([2])

In [60]:
# MATRIX
MATRIX = torch.tensor([[2,4],
                       [1,3]])
MATRIX

tensor([[2, 4],
        [1, 3]])

In [61]:
MATRIX.ndim

2

In [62]:
MATRIX[0]

tensor([2, 4])

In [63]:
MATRIX.shape

torch.Size([2, 2])

In [64]:
# Tensor
TENSOR = torch.tensor([[[1,3,9],
                        [2,4,6],
                        [5,9,7]]])
TENSOR

tensor([[[1, 3, 9],
         [2, 4, 6],
         [5, 9, 7]]])

In [65]:
TENSOR.ndim

3

In [66]:
TENSOR.shape

torch.Size([1, 3, 3])

In [67]:
TENSOR[0]

tensor([[1, 3, 9],
        [2, 4, 6],
        [5, 9, 7]])

In [68]:
MY_TENSOR = torch.tensor([[[
                              [1,3,9,4], # <0
                              [2,4,8,6], # <1
#                              [4,1,6,3]  # <2
#                              ^ ^ ^ ^
#                              0 1 2 3
                            ]]])
MY_TENSOR

tensor([[[[1, 3, 9, 4],
          [2, 4, 8, 6]]]])

In [69]:
MY_TENSOR.ndim

4

In [70]:
MY_TENSOR.shape

torch.Size([1, 1, 2, 4])

## Tensor Exercise

In [71]:
TENSOR = torch.tensor([[1,2,3], [4,5,6]])
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
TENSOR.ndim

2

In [73]:
TENSOR.shape

torch.Size([2, 3])

In [74]:
TENSOR[0]

tensor([1, 2, 3])

In [75]:
TENSOR2 = torch.tensor([
    [2,1,4],
    [1,5,2]
])
TENSOR2

tensor([[2, 1, 4],
        [1, 5, 2]])

In [76]:
TENSOR2.ndim

2

In [77]:
TENSOR2.shape

torch.Size([2, 3])

In [78]:
TENSOR3 = torch.tensor([
    [2,1,4],
    [1,5,2],
    [7,5,9]
])
TENSOR3

tensor([[2, 1, 4],
        [1, 5, 2],
        [7, 5, 9]])

In [79]:
TENSOR3.ndim

2

In [80]:
TENSOR3.shape

torch.Size([3, 3])

In [81]:
TENSOR4 = torch.tensor([[
    [1,2,3,2],
    [7,8,9,7],
    [4,5,6,9]
]])

TENSOR4

tensor([[[1, 2, 3, 2],
         [7, 8, 9, 7],
         [4, 5, 6, 9]]])

In [82]:
TENSOR4.ndim

3

In [83]:
TENSOR4.shape

torch.Size([1, 3, 4])

In [84]:
TENSOR5 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ]
                ]
            ]
        ]
    ]
)

TENSOR5

tensor([[[[[[1, 2],
            [4, 1],
            [6, 8]]]]]])

In [85]:
TENSOR5.ndim # expected 6

6

In [86]:
TENSOR5.shape #expected tensor.Size([1,1,1,1,3,2])

torch.Size([1, 1, 1, 1, 3, 2])

In [87]:
TENSOR6 = torch.tensor(
    [
            [
              [1,2],
              [4,8],
              [3,9]
            ],
            [
              [5,6],
              [7,9],
              [4,1]
            ]

    ]
)

TENSOR6

tensor([[[1, 2],
         [4, 8],
         [3, 9]],

        [[5, 6],
         [7, 9],
         [4, 1]]])

In [88]:
TENSOR6.ndim

3

In [89]:
TENSOR6.shape

torch.Size([2, 3, 2])

In [90]:
TENSOR7 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ],
                [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ]
    ]
)
TENSOR7

tensor([[[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]],



         [[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]]],




        [[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
      

In [91]:
TENSOR7.ndim

6

In [92]:
TENSOR7.shape

torch.Size([2, 2, 3, 2, 3, 2])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors = https://pytorch.org/docs/stable/generated/torch.rand.html

In [93]:
# Create a random tensors of size (3,4)
random_tensors = torch.rand(3, 4)
random_tensors

tensor([[0.5642, 0.9639, 0.8621, 0.1065],
        [0.8330, 0.9173, 0.5170, 0.1780],
        [0.1592, 0.6146, 0.9102, 0.3466]])

In [94]:
random_tensors.ndim

2

In [95]:
random_tensors = torch.rand(10, 8)
random_tensors

tensor([[0.6029, 0.9080, 0.8578, 0.7897, 0.0492, 0.5942, 0.9124, 0.8987],
        [0.7839, 0.2753, 0.5979, 0.1511, 0.1180, 0.1333, 0.8527, 0.5341],
        [0.0846, 0.3203, 0.9513, 0.4736, 0.1917, 0.0930, 0.0894, 0.1734],
        [0.0208, 0.8591, 0.5294, 0.7358, 0.7747, 0.6230, 0.4039, 0.2752],
        [0.2327, 0.2658, 0.0457, 0.3560, 0.9374, 0.8267, 0.3658, 0.1760],
        [0.5228, 0.7278, 0.3978, 0.9310, 0.7594, 0.3448, 0.5729, 0.1292],
        [0.2575, 0.1076, 0.6621, 0.6000, 0.8971, 0.7536, 0.5994, 0.2534],
        [0.5071, 0.4185, 0.2823, 0.1228, 0.2930, 0.0173, 0.5304, 0.2333],
        [0.7404, 0.5662, 0.3056, 0.0322, 0.5621, 0.8560, 0.6239, 0.1078],
        [0.8080, 0.3301, 0.1206, 0.7682, 0.0611, 0.8156, 0.5631, 0.0817]])

In [96]:
random_tensors.ndim

2

In [97]:
random_tensors = torch.rand(10, 100, 100)
random_tensors

tensor([[[4.5318e-01, 3.4450e-01, 2.0211e-01,  ..., 1.8112e-01,
          5.0229e-01, 4.8108e-01],
         [4.5367e-01, 6.8936e-01, 8.9190e-01,  ..., 2.5937e-01,
          6.2403e-01, 8.6375e-01],
         [5.2343e-02, 9.5521e-02, 3.3931e-02,  ..., 8.0128e-01,
          3.9698e-01, 9.0320e-01],
         ...,
         [7.0614e-02, 6.1615e-01, 5.6483e-01,  ..., 7.5625e-01,
          9.9051e-01, 8.8800e-01],
         [2.4021e-01, 7.4360e-01, 1.2096e-01,  ..., 7.9165e-02,
          4.0653e-01, 5.9429e-01],
         [2.1409e-01, 5.3133e-01, 4.7653e-01,  ..., 4.1384e-01,
          2.0036e-02, 4.1634e-04]],

        [[2.3594e-01, 4.9944e-01, 9.5698e-01,  ..., 4.0459e-01,
          2.1056e-01, 5.1951e-01],
         [5.7761e-02, 2.6773e-01, 4.9132e-01,  ..., 6.6481e-01,
          9.4474e-01, 7.8787e-01],
         [9.9713e-01, 7.9133e-01, 7.9586e-01,  ..., 2.5164e-01,
          5.3857e-01, 3.6044e-01],
         ...,
         [2.0289e-01, 1.1018e-01, 4.1757e-01,  ..., 9.9099e-03,
          3.298

In [98]:
random_tensors.ndim

3

In [99]:
random_tensors = torch.rand(10, 10, 10, 10, 10)
random_tensors

tensor([[[[[9.8856e-01, 4.5338e-01, 9.5354e-01,  ..., 5.3671e-01,
            8.4066e-01, 8.7908e-01],
           [3.3141e-01, 5.1594e-01, 4.5940e-01,  ..., 4.0968e-01,
            7.4633e-02, 5.1862e-01],
           [9.1777e-01, 7.2190e-01, 9.4529e-01,  ..., 6.4139e-01,
            1.7745e-01, 5.3947e-01],
           ...,
           [3.9679e-01, 9.5701e-01, 6.9564e-01,  ..., 9.0319e-01,
            1.7255e-01, 3.5790e-01],
           [1.1813e-01, 9.4486e-01, 9.5734e-01,  ..., 1.8626e-01,
            9.0525e-01, 1.2571e-01],
           [3.6571e-01, 3.5422e-01, 1.8993e-01,  ..., 5.9387e-01,
            8.4630e-01, 2.2168e-01]],

          [[1.5020e-01, 8.7197e-01, 3.5977e-01,  ..., 6.7168e-01,
            5.6210e-01, 8.8564e-01],
           [8.5527e-01, 2.9078e-01, 8.0418e-01,  ..., 7.0665e-01,
            4.8444e-01, 9.9353e-01],
           [4.3810e-01, 7.8661e-01, 3.4863e-01,  ..., 9.4088e-01,
            1.0975e-01, 7.0791e-01],
           ...,
           [9.7239e-01, 4.7735e-01, 8.8

In [100]:
random_tensors.ndim

5

In [101]:
random_tensors.shape

torch.Size([10, 10, 10, 10, 10])

In [102]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [103]:
itensor = torch.rand(224, 224, 3)
itensor

tensor([[[0.6600, 0.8323, 0.1576],
         [0.1408, 0.4704, 0.2799],
         [0.6871, 0.3447, 0.4235],
         ...,
         [0.5632, 0.1591, 0.7820],
         [0.7913, 0.5051, 0.6542],
         [0.9272, 0.5478, 0.2432]],

        [[0.1077, 0.6811, 0.0937],
         [0.6150, 0.5299, 0.4587],
         [0.5214, 0.2604, 0.7606],
         ...,
         [0.2779, 0.3019, 0.5154],
         [0.6848, 0.8815, 0.2706],
         [0.2070, 0.8592, 0.4248]],

        [[0.5828, 0.9620, 0.3865],
         [0.9789, 0.9138, 0.5955],
         [0.5086, 0.6065, 0.5051],
         ...,
         [0.2385, 0.4675, 0.8924],
         [0.3806, 0.2859, 0.2789],
         [0.6888, 0.1914, 0.5726]],

        ...,

        [[0.8634, 0.5536, 0.2590],
         [0.1930, 0.7899, 0.2853],
         [0.8656, 0.3131, 0.5948],
         ...,
         [0.2812, 0.6723, 0.7270],
         [0.6824, 0.7598, 0.7485],
         [0.8107, 0.3962, 0.1620]],

        [[0.5777, 0.9782, 0.5774],
         [0.3178, 0.2424, 0.6475],
         [0.

In [104]:
itensor.ndim

3

## Zeros and ones

In [107]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [112]:
new_random_tensor = torch.rand(3,4)
new_random_tensor

tensor([[0.5488, 0.4058, 0.0690, 0.4628],
        [0.6566, 0.5556, 0.8531, 0.8771],
        [0.3811, 0.0547, 0.8033, 0.9676]])

In [113]:
zeros * new_random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [114]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [115]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

`torch.arange()` : https://pytorch.org/docs/stable/generated/torch.arange.html

In [126]:
# Use torch.range(1,11)
# Depreciated message:::>>>> UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).

one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [127]:
zero_to_hundred = torch.arange(start=0, end=100, step=10)
zero_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [128]:
# Creating tensors like
# when we have to define a tensor shape from a pre-defined tensor and overwrite with zeros
new_tensor_from_zero_to_hundred_tensor = torch.zeros_like(input=zero_to_hundred)
new_tensor_from_zero_to_hundred_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])