### PyTorch Fundamentals

In [57]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [58]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [59]:
# number of dimension : https://pytorch.org/docs/stable/generated/torch.Tensor.ndim.html

scalar.ndim

0

In [60]:
# Get tensor back as Python int

scalar.item()

7

In [61]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [62]:
vector.ndim

1

In [63]:
vector.shape

torch.Size([2])

In [64]:
# MATRIX
MATRIX = torch.tensor([[2,4],
                       [1,3]])
MATRIX

tensor([[2, 4],
        [1, 3]])

In [65]:
MATRIX.ndim

2

In [66]:
MATRIX[0]

tensor([2, 4])

In [67]:
MATRIX.shape

torch.Size([2, 2])

In [68]:
# Tensor
TENSOR = torch.tensor([[[1,3,9],
                        [2,4,6],
                        [5,9,7]]])
TENSOR

tensor([[[1, 3, 9],
         [2, 4, 6],
         [5, 9, 7]]])

In [69]:
TENSOR.ndim

3

In [70]:
TENSOR.shape

torch.Size([1, 3, 3])

In [71]:
TENSOR[0]

tensor([[1, 3, 9],
        [2, 4, 6],
        [5, 9, 7]])

In [72]:
MY_TENSOR = torch.tensor([[[
                              [1,3,9,4], # <0
                              [2,4,8,6], # <1
#                              [4,1,6,3]  # <2
#                              ^ ^ ^ ^
#                              0 1 2 3
                            ]]])
MY_TENSOR

tensor([[[[1, 3, 9, 4],
          [2, 4, 8, 6]]]])

In [73]:
MY_TENSOR.ndim

4

In [74]:
MY_TENSOR.shape

torch.Size([1, 1, 2, 4])

## Tensor Exercise

In [75]:
TENSOR = torch.tensor([[1,2,3], [4,5,6]])
TENSOR

tensor([[1, 2, 3],
        [4, 5, 6]])

In [76]:
TENSOR.ndim

2

In [77]:
TENSOR.shape

torch.Size([2, 3])

In [78]:
TENSOR[0]

tensor([1, 2, 3])

In [79]:
TENSOR2 = torch.tensor([
    [2,1,4],
    [1,5,2]
])
TENSOR2

tensor([[2, 1, 4],
        [1, 5, 2]])

In [80]:
TENSOR2.ndim

2

In [81]:
TENSOR2.shape

torch.Size([2, 3])

In [82]:
TENSOR3 = torch.tensor([
    [2,1,4],
    [1,5,2],
    [7,5,9]
])
TENSOR3

tensor([[2, 1, 4],
        [1, 5, 2],
        [7, 5, 9]])

In [83]:
TENSOR3.ndim

2

In [84]:
TENSOR3.shape

torch.Size([3, 3])

In [85]:
TENSOR4 = torch.tensor([[
    [1,2,3,2],
    [7,8,9,7],
    [4,5,6,9]
]])

TENSOR4

tensor([[[1, 2, 3, 2],
         [7, 8, 9, 7],
         [4, 5, 6, 9]]])

In [86]:
TENSOR4.ndim

3

In [87]:
TENSOR4.shape

torch.Size([1, 3, 4])

In [88]:
TENSOR5 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ]
                ]
            ]
        ]
    ]
)

TENSOR5

tensor([[[[[[1, 2],
            [4, 1],
            [6, 8]]]]]])

In [89]:
TENSOR5.ndim # expected 6

6

In [90]:
TENSOR5.shape #expected tensor.Size([1,1,1,1,3,2])

torch.Size([1, 1, 1, 1, 3, 2])

In [91]:
TENSOR6 = torch.tensor(
    [
            [
              [1,2],
              [4,8],
              [3,9]
            ],
            [
              [5,6],
              [7,9],
              [4,1]
            ]

    ]
)

TENSOR6

tensor([[[1, 2],
         [4, 8],
         [3, 9]],

        [[5, 6],
         [7, 9],
         [4, 1]]])

In [92]:
TENSOR6.ndim

3

In [93]:
TENSOR6.shape

torch.Size([2, 3, 2])

In [113]:
TENSOR7 = torch.tensor(
    [
        [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ],
                [
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ],
            [
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ],
                [
                    [
                        [1,2],
                        [4,1],
                        [6,8]
                    ],
                    [
                        [4,1],
                        [1,5],
                        [47,9]
                    ]
                ]
            ]
        ]
    ]
)
TENSOR7

tensor([[[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]],



         [[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]]]],




        [[[[[ 1,  2],
            [ 4,  1],
            [ 6,  8]],

           [[ 4,  1],
            [ 1,  5],
            [47,  9]]],


          [[[ 1,  2],
      

In [114]:
TENSOR7.ndim

6

In [115]:
TENSOR7.shape

torch.Size([2, 2, 3, 2, 3, 2])