# Exercises

## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)
* The documentation on [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html)

In [64]:
import torch

In [65]:
# default float datatype is `float32`

default_float_datatype_tensor = torch.tensor([0.5, 0.1, 0.7, 0.3])
default_float_datatype_tensor, default_float_datatype_tensor.dtype

(tensor([0.5000, 0.1000, 0.7000, 0.3000]), torch.float32)

In [66]:
# torch.Tensor

## Data Types

# float32 datatype
# create tensor
float_32_tensor = torch.tensor([4, 7, 8], dtype=torch.float) # `torch.float` or, `torch.float32`
float_32_tensor, float_32_tensor.dtype

(tensor([4., 7., 8.]), torch.float32)

In [67]:
float_32Tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
float_32Tensor

tensor([1., 2., 3.])

In [68]:
# float64 datatype
float_64_tensor = torch.tensor([1, 4, 2], dtype=torch.float64) # `torch.float64` or, `torch.double`
float_64_tensor, float_64_tensor.dtype

(tensor([1., 4., 2.], dtype=torch.float64), torch.float64)

In [69]:
float_64Tensor = torch.tensor([6, 9, 2], dtype=torch.double)
float_64Tensor, float_64Tensor.dtype

(tensor([6., 9., 2.], dtype=torch.float64), torch.float64)

In [70]:
'''
1. Sometimes referred to as binary16: uses 1 sign, 5 exponent, and 10 significand bits. Useful when precision is important at the expense of range.
'''

# 1. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.float16), torch.float16)

In [71]:
#
float_16Tensor = torch.tensor([8, 2, 6], dtype=torch.half)
float_16Tensor, float_16Tensor.dtype

(tensor([8., 2., 6.], dtype=torch.float16), torch.float16)

In [72]:
'''
Sometimes referred to as Brain Floating Point: uses 1 sign, 8 exponent, and 7 significand bits. Useful when range is important, since it has the same number of exponent bits as float32
'''

# 2. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.bfloat16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.bfloat16), torch.bfloat16)

In [73]:
# default integer datatype is `int64`
default_int_datatype_tensor = torch.tensor([6,1,9])
default_int_datatype_tensor, default_int_datatype_tensor.dtype

(tensor([6, 1, 9]), torch.int64)

In [74]:
# integers(signed) datatypes
int_8_tensor = torch.tensor([4,8,1], dtype=torch.int8)
int_8_tensor, int_8_tensor.dtype

(tensor([4, 8, 1], dtype=torch.int8), torch.int8)

In [75]:
int_16_tensor = torch.tensor([6,8,2], dtype=torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([6, 8, 2], dtype=torch.int16), torch.int16)

In [76]:
int_16_or_short_tensor = torch.tensor([7,1,9], dtype=torch.short)
int_16_or_short_tensor, int_16_or_short_tensor.dtype

(tensor([7, 1, 9], dtype=torch.int16), torch.int16)

In [77]:
# 32bit integers (signed)
int_32_tensor = torch.tensor([6,3,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([6, 3, 9], dtype=torch.int32), torch.int32)

In [78]:
int32Tensor = torch.tensor([6,1,9], dtype=torch.int)
int32Tensor, int32Tensor.dtype

(tensor([6, 1, 9], dtype=torch.int32), torch.int32)

In [79]:
int_64_Tensor = torch.tensor([7,1,8], dtype=torch.int64)
int_64_Tensor, int_64_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [80]:
int_64_or_long_Tensor = torch.tensor([7,1,8], dtype=torch.long)
int_64_or_long_Tensor, int_64_or_long_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [81]:
# boolean datatype
boolean_tensor = torch.tensor([1,0,1,0,1], dtype=torch.bool)
boolean_tensor, boolean_tensor.dtype

(tensor([ True, False,  True, False,  True]), torch.bool)

In [82]:
## backward compatibility
# 32-bit floating point
x = torch.FloatTensor([1,8,5])
x, x.dtype

(tensor([1., 8., 5.]), torch.float32)

In [83]:
# converting datatype (float32 to float64)

# 1.
y = x.type(torch.DoubleTensor)
y, y.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [84]:
# 2.
z = x.type(torch.float64)
z, z.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [85]:
# 3.
w = x.type(torch.double)
w, w.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [86]:
# 64-bit floating point
a = torch.DoubleTensor([7,1,5,4])
a

tensor([7., 1., 5., 4.], dtype=torch.float64)

In [87]:
# 16-bit floating point
b = torch.HalfTensor([4,7,1])
b

tensor([4., 7., 1.], dtype=torch.float16)

In [88]:
# 16-bit floating point
c = torch.BFloat16Tensor([5,8,4])
c

tensor([5., 8., 4.], dtype=torch.bfloat16)

In [89]:
# 8-bit integer (unsigned)
d = torch.ByteTensor([1,2,3])
d

tensor([1, 2, 3], dtype=torch.uint8)

In [90]:
# 8-bit integer (signed)
e = torch.CharTensor([3,5,4])
e

tensor([3, 5, 4], dtype=torch.int8)

In [91]:
# 16-bit integer (signed)
f = torch.ShortTensor([5,7,9])
f

tensor([5, 7, 9], dtype=torch.int16)

In [92]:
# 32-bit integer (signed)
g = torch.IntTensor([6,1,5])
g

tensor([6, 1, 5], dtype=torch.int32)

In [93]:
# 64-bit integer (signed)
h = torch.LongTensor([5,2,9])
h

tensor([5, 2, 9])

In [94]:
# Boolean
i = torch.BoolTensor([0,1,0])
i, i.dtype

(tensor([False,  True, False]), torch.bool)

In [95]:
# factory function - `torch.empty()`
k = torch.empty(size=(3,3),dtype=torch.float16)
k, k.ndim, k.shape

(tensor([[6.5565e-06, 0.0000e+00, 5.9605e-07],
         [0.0000e+00, 6.2585e-06, 0.0000e+00],
         [1.9073e-06, 0.0000e+00, 3.6359e-06]], dtype=torch.float16),
 2,
 torch.Size([3, 3]))

In [96]:
# initializing and basic operations
m = torch.tensor([
    [1., -1.],
    [1., -1.]
])
m

tensor([[ 1., -1.],
        [ 1., -1.]])

In [97]:
import numpy as np

from_numpy = torch.tensor(
    np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])
)
from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [98]:
check = torch.tensor([1, 2, 3], dtype=torch.float16)
check.requires_grad_()

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [99]:
# another method
check2 = torch.tensor([1.0, 4.1, 9.2])
check2.detach_(), check2.dtype

(tensor([1.0000, 4.1000, 9.2000]), torch.float32)

In [100]:
y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
y

<ipython-input-100-94b980d24cc2>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


tensor([1.0000, 4.1000, 9.2000])

In [101]:
#
TENSOR_X = torch.tensor([2.1, 6.4, 3.9], requires_grad=True)

TENSOR_Y = TENSOR_X.detach()

TENSOR_Y.requires_grad_()

tensor([2.1000, 6.4000, 3.9000], requires_grad=True)

In [102]:
checkTensor = torch.Tensor([1, 2, 3])
checkTensor, checkTensor.dtype

(tensor([1., 2., 3.]), torch.float32)

# Tensor class reference
```
class     torch.Tensor
```
There are a few main ways to create a tensor, depending on your use case.

1. To create a tensor with pre-existing data, use `torch.tensor()`.

2. To create a tensor with specific size, use `torch.*` tensor creation ops (see [Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)).

3. To create a tensor with the same size (and similar types) as another tensor, use `torch.*_like` tensor creation ops (see [Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)).

4. To create a tensor with similar type but different size as another tensor, use `tensor.new_*` creation ops.



In [103]:
# 1
first_tensor = torch.tensor([6, 3, 2])
first_tensor

tensor([6, 3, 2])

In [104]:
# 2 torch.*

# 2.1 - torch.zeros(dimension or size)
second_tensor = torch.zeros(3, 4)
second_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [105]:
# 2.2 torch.zeros_like(source_tensor)
source_tensor = torch.tensor([[3, 4, 6], [1, 8, 3]])

third_tensor = torch.zeros_like(source_tensor)
third_tensor

tensor([[0, 0, 0],
        [0, 0, 0]])

In [106]:
# 2.3 torch.ones(dimension)
ones_tensor = torch.ones(5,8)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [107]:
# 2.4 torch.ones_like(source_tensor)
source_tensor = torch.tensor([[3, 6, 7], [9,5,8]])
ones_like_tensor = torch.ones_like(source_tensor)
print(f"source_tensor = \n{source_tensor}")
print(f"ones_like_tensor = \n{ones_like_tensor}")

source_tensor = 
tensor([[3, 6, 7],
        [9, 5, 8]])
ones_like_tensor = 
tensor([[1, 1, 1],
        [1, 1, 1]])


In [108]:
# 2.5 torch.arange(start, end, step) - returns a 1-D tensor of size [end - start / step]
arange_tensor = torch.arange(1, 15, 2)
arange_tensor

tensor([ 1,  3,  5,  7,  9, 11, 13])

In [109]:
# 2.6 torch.linspace(start, end, step) - Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
linspace_tensor = torch.linspace(60, 100, 14)
linspace_tensor

tensor([ 60.0000,  63.0769,  66.1538,  69.2308,  72.3077,  75.3846,  78.4615,
         81.5385,  84.6154,  87.6923,  90.7692,  93.8462,  96.9231, 100.0000])

In [110]:
# 2.7 torch.logspace(start, end, step, base) - Creates a one-dimensional tensor of size steps whose values are evenly spaced from base start base_start to base_end base end, inclusive, on a logarithmic scale with base base.
logspace_tensor = torch.logspace(3, 9, 5) # by default base=10.0
logspace_tensor

tensor([1.0000e+03, 3.1623e+04, 1.0000e+06, 3.1623e+07, 1.0000e+09])

In [111]:
'''
calculation for getting the values of the return Tensor,
value = base ** (start + i * (end-start) / (steps-1)),   where `i` is the index of the value in the sequence, ranging from 0 to `steps-1`
'''

logspace_tensor = torch.logspace(0, 2, 10)
logspace_tensor

tensor([  1.0000,   1.6681,   2.7826,   4.6416,   7.7426,  12.9155,  21.5443,
         35.9381,  59.9484, 100.0000])

In [114]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=1)
exploring_logspace

tensor([1.2589])

In [115]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=2)
exploring_logspace

tensor([ 1.2589, 10.0000])

In [116]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=3)
exploring_logspace

tensor([ 1.2589,  3.5481, 10.0000])

In [117]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=4)
exploring_logspace

tensor([ 1.2589,  2.5119,  5.0119, 10.0000])

In [134]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=5)
exploring_logspace

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [127]:
0.9 / 4

0.225

In [131]:
0.225 * 2

0.45

In [132]:
0.45+0.1

0.55

In [133]:
10 ** 0.55

3.548133892335755

# Indexing, Slicing, Joining, Mutating Ops[