# Exercises

## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

* The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html)
* The documentation on [`torch.cuda`](https://pytorch.org/docs/stable/cuda.html)

In [2]:
import torch

In [3]:
# default float datatype is `float32`

default_float_datatype_tensor = torch.tensor([0.5, 0.1, 0.7, 0.3])
default_float_datatype_tensor, default_float_datatype_tensor.dtype

(tensor([0.5000, 0.1000, 0.7000, 0.3000]), torch.float32)

In [4]:
# torch.Tensor

## Data Types

# float32 datatype
# create tensor
float_32_tensor = torch.tensor([4, 7, 8], dtype=torch.float) # `torch.float` or, `torch.float32`
float_32_tensor, float_32_tensor.dtype

(tensor([4., 7., 8.]), torch.float32)

In [5]:
float_32Tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
float_32Tensor

tensor([1., 2., 3.])

In [6]:
# float64 datatype
float_64_tensor = torch.tensor([1, 4, 2], dtype=torch.float64) # `torch.float64` or, `torch.double`
float_64_tensor, float_64_tensor.dtype

(tensor([1., 4., 2.], dtype=torch.float64), torch.float64)

In [7]:
float_64Tensor = torch.tensor([6, 9, 2], dtype=torch.double)
float_64Tensor, float_64Tensor.dtype

(tensor([6., 9., 2.], dtype=torch.float64), torch.float64)

In [8]:
'''
1. Sometimes referred to as binary16: uses 1 sign, 5 exponent, and 10 significand bits. Useful when precision is important at the expense of range.
'''

# 1. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.float16), torch.float16)

In [9]:
#
float_16Tensor = torch.tensor([8, 2, 6], dtype=torch.half)
float_16Tensor, float_16Tensor.dtype

(tensor([8., 2., 6.], dtype=torch.float16), torch.float16)

In [10]:
'''
Sometimes referred to as Brain Floating Point: uses 1 sign, 8 exponent, and 7 significand bits. Useful when range is important, since it has the same number of exponent bits as float32
'''

# 2. float16 datatype
float_16_tensor = torch.tensor([7, 3, 4], dtype=torch.bfloat16)
float_16_tensor, float_16_tensor.dtype

(tensor([7., 3., 4.], dtype=torch.bfloat16), torch.bfloat16)

In [11]:
# default integer datatype is `int64`
default_int_datatype_tensor = torch.tensor([6,1,9])
default_int_datatype_tensor, default_int_datatype_tensor.dtype

(tensor([6, 1, 9]), torch.int64)

In [12]:
# integers(signed) datatypes
int_8_tensor = torch.tensor([4,8,1], dtype=torch.int8)
int_8_tensor, int_8_tensor.dtype

(tensor([4, 8, 1], dtype=torch.int8), torch.int8)

In [13]:
int_16_tensor = torch.tensor([6,8,2], dtype=torch.int16)
int_16_tensor, int_16_tensor.dtype

(tensor([6, 8, 2], dtype=torch.int16), torch.int16)

In [14]:
int_16_or_short_tensor = torch.tensor([7,1,9], dtype=torch.short)
int_16_or_short_tensor, int_16_or_short_tensor.dtype

(tensor([7, 1, 9], dtype=torch.int16), torch.int16)

In [15]:
# 32bit integers (signed)
int_32_tensor = torch.tensor([6,3,9], dtype=torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([6, 3, 9], dtype=torch.int32), torch.int32)

In [16]:
int32Tensor = torch.tensor([6,1,9], dtype=torch.int)
int32Tensor, int32Tensor.dtype

(tensor([6, 1, 9], dtype=torch.int32), torch.int32)

In [17]:
int_64_Tensor = torch.tensor([7,1,8], dtype=torch.int64)
int_64_Tensor, int_64_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [18]:
int_64_or_long_Tensor = torch.tensor([7,1,8], dtype=torch.long)
int_64_or_long_Tensor, int_64_or_long_Tensor.dtype

(tensor([7, 1, 8]), torch.int64)

In [19]:
# boolean datatype
boolean_tensor = torch.tensor([1,0,1,0,1], dtype=torch.bool)
boolean_tensor, boolean_tensor.dtype

(tensor([ True, False,  True, False,  True]), torch.bool)

In [20]:
## backward compatibility
# 32-bit floating point
x = torch.FloatTensor([1,8,5])
x, x.dtype

(tensor([1., 8., 5.]), torch.float32)

In [21]:
# converting datatype (float32 to float64)

# 1.
y = x.type(torch.DoubleTensor)
y, y.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [22]:
# 2.
z = x.type(torch.float64)
z, z.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [23]:
# 3.
w = x.type(torch.double)
w, w.dtype

(tensor([1., 8., 5.], dtype=torch.float64), torch.float64)

In [24]:
# 64-bit floating point
a = torch.DoubleTensor([7,1,5,4])
a

tensor([7., 1., 5., 4.], dtype=torch.float64)

In [25]:
# 16-bit floating point
b = torch.HalfTensor([4,7,1])
b

tensor([4., 7., 1.], dtype=torch.float16)

In [26]:
# 16-bit floating point
c = torch.BFloat16Tensor([5,8,4])
c

tensor([5., 8., 4.], dtype=torch.bfloat16)

In [27]:
# 8-bit integer (unsigned)
d = torch.ByteTensor([1,2,3])
d

tensor([1, 2, 3], dtype=torch.uint8)

In [28]:
# 8-bit integer (signed)
e = torch.CharTensor([3,5,4])
e

tensor([3, 5, 4], dtype=torch.int8)

In [29]:
# 16-bit integer (signed)
f = torch.ShortTensor([5,7,9])
f

tensor([5, 7, 9], dtype=torch.int16)

In [30]:
# 32-bit integer (signed)
g = torch.IntTensor([6,1,5])
g

tensor([6, 1, 5], dtype=torch.int32)

In [31]:
# 64-bit integer (signed)
h = torch.LongTensor([5,2,9])
h

tensor([5, 2, 9])

In [32]:
# Boolean
i = torch.BoolTensor([0,1,0])
i, i.dtype

(tensor([False,  True, False]), torch.bool)

In [33]:
# factory function - `torch.empty()`
k = torch.empty(size=(3,3),dtype=torch.float16)
k, k.ndim, k.shape

(tensor([[ 2.7660e+03,  1.3900e+03,  7.6660e-01],
         [ 1.1963e-02,  6.7353e-06,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, -4.4556e-03]], dtype=torch.float16),
 2,
 torch.Size([3, 3]))

In [34]:
# initializing and basic operations
m = torch.tensor([
    [1., -1.],
    [1., -1.]
])
m

tensor([[ 1., -1.],
        [ 1., -1.]])

In [35]:
import numpy as np

from_numpy = torch.tensor(
    np.array([
        [1, 2, 3],
        [4, 5, 6]
    ])
)
from_numpy

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
check = torch.tensor([1, 2, 3], dtype=torch.float16)
check.requires_grad_()

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [37]:
# another method
check2 = torch.tensor([1.0, 4.1, 9.2])
check2.detach_(), check2.dtype

(tensor([1.0000, 4.1000, 9.2000]), torch.float32)

In [38]:
y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
y

<ipython-input-38-94b980d24cc2>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(check2) # To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


tensor([1.0000, 4.1000, 9.2000])

In [39]:
#
TENSOR_X = torch.tensor([2.1, 6.4, 3.9], requires_grad=True)

TENSOR_Y = TENSOR_X.detach()

TENSOR_Y.requires_grad_()

tensor([2.1000, 6.4000, 3.9000], requires_grad=True)

In [40]:
checkTensor = torch.Tensor([1, 2, 3])
checkTensor, checkTensor.dtype

(tensor([1., 2., 3.]), torch.float32)

# Tensor class reference
```
class     torch.Tensor
```
There are a few main ways to create a tensor, depending on your use case.

1. To create a tensor with pre-existing data, use `torch.tensor()`.

2. To create a tensor with specific size, use `torch.*` tensor creation ops (see [Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)).

3. To create a tensor with the same size (and similar types) as another tensor, use `torch.*_like` tensor creation ops (see [Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops)).

4. To create a tensor with similar type but different size as another tensor, use `tensor.new_*` creation ops.



In [41]:
# 1
first_tensor = torch.tensor([6, 3, 2])
first_tensor

tensor([6, 3, 2])

In [42]:
# 2 torch.*

# 2.1 - torch.zeros(dimension or size)
second_tensor = torch.zeros(3, 4)
second_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [43]:
# 2.2 torch.zeros_like(source_tensor)
source_tensor = torch.tensor([[3, 4, 6], [1, 8, 3]])

third_tensor = torch.zeros_like(source_tensor)
third_tensor

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
# 2.3 torch.ones(dimension)
ones_tensor = torch.ones(5,8)
ones_tensor

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
# 2.4 torch.ones_like(source_tensor)
source_tensor = torch.tensor([[3, 6, 7], [9,5,8]])
ones_like_tensor = torch.ones_like(source_tensor)
print(f"source_tensor = \n{source_tensor}")
print(f"ones_like_tensor = \n{ones_like_tensor}")

source_tensor = 
tensor([[3, 6, 7],
        [9, 5, 8]])
ones_like_tensor = 
tensor([[1, 1, 1],
        [1, 1, 1]])


In [46]:
# 2.5 torch.arange(start, end, step) - returns a 1-D tensor of size [end - start / step]
arange_tensor = torch.arange(1, 15, 2)
arange_tensor

tensor([ 1,  3,  5,  7,  9, 11, 13])

In [47]:
# 2.6 torch.linspace(start, end, step) - Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.
linspace_tensor = torch.linspace(60, 100, 14)
linspace_tensor

tensor([ 60.0000,  63.0769,  66.1538,  69.2308,  72.3077,  75.3846,  78.4615,
         81.5385,  84.6154,  87.6923,  90.7692,  93.8462,  96.9231, 100.0000])

In [48]:
# 2.7 torch.logspace(start, end, step, base) - Creates a one-dimensional tensor of size steps whose values are evenly spaced from base start base_start to base_end base end, inclusive, on a logarithmic scale with base base.
logspace_tensor = torch.logspace(3, 9, 5) # by default base=10.0
logspace_tensor

tensor([1.0000e+03, 3.1623e+04, 1.0000e+06, 3.1623e+07, 1.0000e+09])

In [49]:
'''
calculation for getting the values of the return Tensor,
value = base ** (start + i * (end-start) / (steps-1)),   where `i` is the index of the value in the sequence, ranging from 0 to `steps-1`
'''

logspace_tensor = torch.logspace(0, 2, 10)
logspace_tensor

tensor([  1.0000,   1.6681,   2.7826,   4.6416,   7.7426,  12.9155,  21.5443,
         35.9381,  59.9484, 100.0000])

In [50]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=1)
exploring_logspace

tensor([1.2589])

In [51]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=2)
exploring_logspace

tensor([ 1.2589, 10.0000])

In [52]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=3)
exploring_logspace

tensor([ 1.2589,  3.5481, 10.0000])

In [53]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=4)
exploring_logspace

tensor([ 1.2589,  2.5119,  5.0119, 10.0000])

In [54]:
exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=5)
exploring_logspace

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [55]:
'''
calculation of `torch.logspace(start=0.1, end=1.0, steps=10)`

values of the return tensor are:

1st_value  = base ** (start + (steps - 10) * (end - start / steps - 1)) [equivalent of (base ** start), if you put those values in the equation you will understand why it's equivalent with `base ** start`]
2nd_value  = base ** (start + (steps - 9) * (end - start / steps - 1))
3rd_value  = base ** (start + (steps - 8) * (end - start / steps - 1))
4th_value  = base ** (start + (steps - 7) * (end - start / steps - 1))
5th_value  = base ** (start + (steps - 6) * (end - start / steps - 1))
6th_value  = base ** (start + (steps - 5) * (end - start / steps - 1))
7th_value  = base ** (start + (steps - 4) * (end - start / steps - 1))
6th_value  = base ** (start + (steps - 3) * (end - start / steps - 1))
8th_value  = base ** (start + (steps - 2) * (end - start / steps - 1))
10th_value = base ** (start + (steps - 1) * (end - start / steps - 1)) [equivalent of (base ** end), if you put those values in the equation you will understand why it's equivalent with `base ** end`]

notice: for user defined purposes if we mention `i` instead of (steps - 10, 9, 8, 7, 6, 5, 4, 3, 2, 1) that means the index of the `i` will be start `0` to `steps - 1`
        as for this example 0 to 9 because `steps = 10`

source: https://pytorch.org/docs/stable/generated/torch.logspace.html#torch.logspace
'''


exploring_logspace = torch.logspace(start=0.1, end=1.0, steps=10)
exploring_logspace

tensor([ 1.2589,  1.5849,  1.9953,  2.5119,  3.1623,  3.9811,  5.0119,  6.3096,
         7.9433, 10.0000])

In [56]:
# 2.8 torch.eye() -> Returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
eye_tensor = torch.eye(5) # paramers of eye() are, 1. n (which will be a int number) -> the number of rows 2. m (which will be a int number) -> the number of columns with default being n
eye_tensor, eye_tensor.shape, eye_tensor.ndim

(tensor([[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.]]),
 torch.Size([5, 5]),
 2)

In [57]:
eye_tensor = torch.eye(8, 8)
eye_tensor, eye_tensor.shape, eye_tensor.ndim

(tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1.]]),
 torch.Size([8, 8]),
 2)

In [58]:
# 2.9 - torch.empty(size of the tensor) -> Return a tensor filled with uninitialized data.
empty_tensor = torch.empty((3, 4))
empty_tensor

tensor([[3.9765e+03, 3.2924e-41, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.3682e+03, 3.2924e-41, 1.3593e-43, 0.0000e+00]])

In [59]:
# 3.0 - torch.empty_like(input_tensor) -> Returns an uninitialized tensor with the same size as input.
input_tensor = torch.empty((3, 4), dtype=torch.int32)

empty_like_tensor = torch.empty_like(input_tensor)
empty_like_tensor

tensor([[-111692672,      23490, -111764080,      23490],
        [         1,          0, -111785920,      23490],
        [ 561194592,      31315, -111785920,      23490]], dtype=torch.int32)

In [60]:
# 3.1 ->

In [61]:
x = torch.rand(3, 100)
x, x.shape, x.ndim

(tensor([[8.8044e-02, 6.3602e-02, 8.8195e-01, 8.5240e-02, 3.1369e-01, 2.6944e-01,
          8.6670e-01, 9.5565e-01, 3.0780e-01, 7.5683e-01, 2.0725e-01, 3.4714e-01,
          4.6998e-01, 2.0735e-01, 6.5807e-01, 9.5615e-01, 5.8262e-01, 2.5419e-01,
          4.4357e-01, 2.9295e-01, 7.8577e-01, 3.9001e-01, 8.9745e-02, 5.3600e-01,
          9.8041e-01, 7.5764e-01, 1.7787e-01, 5.6074e-01, 4.3668e-01, 3.8820e-01,
          5.9794e-02, 6.8732e-01, 4.3531e-02, 8.2958e-01, 2.7647e-01, 3.3656e-01,
          4.4210e-01, 7.0750e-01, 6.4048e-01, 8.3917e-01, 3.8662e-01, 8.6251e-01,
          6.5511e-01, 2.9556e-02, 4.9676e-01, 6.4653e-01, 6.6580e-01, 9.8931e-01,
          9.5600e-01, 8.7140e-01, 2.6837e-01, 5.8115e-01, 7.9386e-03, 1.0414e-02,
          2.8151e-01, 7.5777e-01, 2.0565e-01, 7.4992e-01, 1.5739e-01, 5.8599e-01,
          3.0448e-01, 2.8610e-02, 6.4476e-01, 5.8234e-01, 6.0530e-01, 5.8118e-01,
          3.7200e-01, 4.7594e-01, 3.6924e-02, 1.8307e-01, 7.6388e-02, 1.4817e-02,
          6.8327

In [62]:
x.stride()

(100, 1)

In [63]:
# Create a 2D array
x = torch.tensor(
    [

              [0, 1, 2, 3, 4,7],
              [5, 6, 7, 8, 9,8],

    ], dtype=torch.int32)

x.stride(), x.ndim

((6, 1), 2)

In [64]:
x[0][0].item() #x_00

0

In [65]:
#x_10
x[1][0]

tensor(5, dtype=torch.int32)

In [66]:
import numpy as np

t = torch.tensor(np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], dtype=np.int32))
t.stride()

(5, 1)

In [67]:
x = torch.arange(12).view((3,4))
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [68]:
idx = (2, 1)
item = x[idx].item()
item

9

In [87]:
# torch.squeeze()
x = torch.rand(1,5,3,1,2,1)

print({x}, {x.ndim}, {x.shape})

sq = torch.squeeze(x)
print({sq}, {sq.ndim}, {sq.shape})

{tensor([[[[[[0.8549],
            [0.5509]]],


          [[[0.2868],
            [0.2063]]],


          [[[0.4451],
            [0.3593]]]],



         [[[[0.7204],
            [0.0731]]],


          [[[0.9699],
            [0.1078]]],


          [[[0.8829],
            [0.4132]]]],



         [[[[0.7572],
            [0.6948]]],


          [[[0.5209],
            [0.5932]]],


          [[[0.8797],
            [0.6286]]]],



         [[[[0.7653],
            [0.1132]]],


          [[[0.8559],
            [0.6721]]],


          [[[0.6267],
            [0.5691]]]],



         [[[[0.7437],
            [0.9592]]],


          [[[0.3887],
            [0.2214]]],


          [[[0.3742],
            [0.1953]]]]]])} {6} {torch.Size([1, 5, 3, 1, 2, 1])}
{tensor([[[0.8549, 0.5509],
         [0.2868, 0.2063],
         [0.4451, 0.3593]],

        [[0.7204, 0.0731],
         [0.9699, 0.1078],
         [0.8829, 0.4132]],

        [[0.7572, 0.6948],
         [0.5209, 0.5932],
         [0

In [91]:
# torch.unsqueeze() -> Returns a new tensor with a dimension of size one inserted at the specified position.
us = torch.unsqueeze(sq, 2)
print({us}, {us.shape}, {us.ndim})

{tensor([[[[0.8549, 0.5509]],

         [[0.2868, 0.2063]],

         [[0.4451, 0.3593]]],


        [[[0.7204, 0.0731]],

         [[0.9699, 0.1078]],

         [[0.8829, 0.4132]]],


        [[[0.7572, 0.6948]],

         [[0.5209, 0.5932]],

         [[0.8797, 0.6286]]],


        [[[0.7653, 0.1132]],

         [[0.8559, 0.6721]],

         [[0.6267, 0.5691]]],


        [[[0.7437, 0.9592]],

         [[0.3887, 0.2214]],

         [[0.3742, 0.1953]]]])} {torch.Size([5, 3, 1, 2])} {4}


# Indexing, Slicing, Joining, Mutating Ops[

# [2. Create a random tensor with shape(7,7)](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [70]:
# create random tensor
random_tensor = torch.randn(7, 7)
random_tensor

tensor([[ 1.7960,  0.0664, -0.1379,  0.1600,  0.1694,  1.3935,  0.4854],
        [ 1.4234,  0.4005, -0.7899,  0.1215, -0.7202, -0.0455,  1.7585],
        [ 0.3135,  0.2611,  1.1616,  0.2869, -1.1168, -1.6596,  1.9179],
        [-0.1791,  0.6051,  0.4286,  0.4196, -0.7494,  0.1484,  0.2248],
        [ 0.5402, -0.5034, -0.0051, -1.3855, -0.0237, -1.5907,  0.7113],
        [-0.2446, -0.4792, -0.0748, -1.9085, -0.2709,  1.3819, -0.1018],
        [-1.7180,  1.0361,  0.5801, -0.6172, -0.1982,  1.2178,  0.0459]])

# [3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape(1,7) (hint: you may have to transpose the second tensor)](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [71]:
second_random_tensor = torch.randn(1, 7)
second_random_tensor

tensor([[ 0.0472, -3.0259,  1.3833, -1.8704,  0.3775, -1.4348, -0.6533]])

In [72]:
# multiplication
#mul_tensor = torch.matmul(random_tensor, second_random_tensor) # generate error because of shape issue(mat1 and mat2 shapes cannot be multiplied (7x7 and 1x7))
#mul_tensor

In [73]:
# hence we have to transpose second_random_tensor to solve the issue
transpose_of_second_random_tensor = second_random_tensor.T
transpose_of_second_random_tensor

tensor([[ 0.0472],
        [-3.0259],
        [ 1.3833],
        [-1.8704],
        [ 0.3775],
        [-1.4348],
        [-0.6533]])

In [74]:
# again try to multiplication
mul_tensor = torch.matmul(random_tensor, transpose_of_second_random_tensor)
mul_tensor

tensor([[-2.8585],
        [-3.8199],
        [ 1.0017],
        [-2.6741],
        [ 5.9419],
        [ 2.8861],
        [-3.1114]])

#[4. Set the random seed to 0 and do exercises 2 & 3 over again.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [75]:
# set the manual seed
torch.manual_seed(0)

# create two random tensor
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

#[5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to `1234`.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [76]:
# set the random seed on the GPU
torch.cuda.manual_seed(1234)

# [6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [77]:
# set random seed
torch.manual_seed(1234)

# check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)

# create two random tensors on GPU
tensor1 = torch.rand(2, 3).to(device)
print(tensor1)
tensor2 = torch.rand(2, 3).to(device)
print(tensor2)



cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


# [7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [78]:
# transpose of second tensor(tensor2)
transpose_of_tensor2 = tensor2.T
print(transpose_of_tensor2.shape)

# multiplication
mul_tensor1_tensor2 = torch.matmul(tensor1, transpose_of_tensor2)
mul_tensor1_tensor2, mul_tensor1_tensor2.shape

torch.Size([3, 2])


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

# [8. Find the maximum and minimum values of the output of exercise no. 7](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [79]:
# maximum
max_of_mul_tensor1_tensor2 = torch.max(mul_tensor1_tensor2)
print(max_of_mul_tensor1_tensor2)

# minimum
min_of_mul_tensor1_tensor2 = torch.min(mul_tensor1_tensor2)
print(min_of_mul_tensor1_tensor2)

tensor(0.5617)
tensor(0.3647)


# [9. Find the maximum and minimum index values of the output of exercise no. 7.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [80]:
#
arg_max = torch.argmax(mul_tensor1_tensor2)

arg_min = torch.argmin(mul_tensor1_tensor2)

arg_max, arg_min

(tensor(3), tensor(0))

In [81]:
torch.manual_seed(1111)
t = torch.rand(5,10,10)
print(t)
print(t.ndim)

print(torch.max(t))
print(torch.min(t))

print(torch.argmax(t))
print(torch.argmin(t))

tensor([[[0.4606, 0.0850, 0.8009, 0.3972, 0.9548, 0.5982, 0.4821, 0.9446,
          0.5145, 0.8125],
         [0.3122, 0.9756, 0.8747, 0.7186, 0.3945, 0.4090, 0.8398, 0.7494,
          0.8129, 0.3084],
         [0.3856, 0.0044, 0.3022, 0.1679, 0.3270, 0.7481, 0.7058, 0.7362,
          0.4007, 0.3604],
         [0.3799, 0.2386, 0.2630, 0.6923, 0.6288, 0.2374, 0.7273, 0.2219,
          0.0023, 0.0519],
         [0.6212, 0.0702, 0.1679, 0.7474, 0.3838, 0.8765, 0.0847, 0.0438,
          0.0240, 0.8543],
         [0.9728, 0.9800, 0.8626, 0.3807, 0.2407, 0.1545, 0.1941, 0.2021,
          0.1576, 0.2454],
         [0.6102, 0.9753, 0.2276, 0.8281, 0.0622, 0.8240, 0.7640, 0.5675,
          0.3867, 0.2336],
         [0.0367, 0.9595, 0.7285, 0.1776, 0.7983, 0.0488, 0.4074, 0.6836,
          0.7789, 0.5250],
         [0.3852, 0.5046, 0.3091, 0.3106, 0.4996, 0.0484, 0.8811, 0.7156,
          0.5041, 0.5557],
         [0.2471, 0.7452, 0.6895, 0.1305, 0.5353, 0.9120, 0.3374, 0.9799,
          0.1652,

In [82]:
mul_tensor1_tensor2

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

# [10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.](https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises)

In [83]:
# create random tensor
torch.manual_seed(7)
r_tensor = torch.rand(1, 1, 1, 10)
print(r_tensor)
print(r_tensor.shape)

# remove the single dimensions
new_tensor = torch.squeeze(r_tensor)
print(new_tensor)
print(new_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
